### ISSUE TITLE
Dockerize Application

### ISSUE THREAD

**Issue by crisr15** [harvard-lts/CURIOSity#1]

**Comment by phil-plencner-hl** [comment]
Steps that I remember needing to install CURIOSity locally:
1. Set up GitLab Token: https://playbook-staging.notch8.com/en/git/gitlab/access-tokens
2. Set up Docker Hub Token the same way: https://hub.docker.com
3. `docker login`
4. `docker login registry.gitlab.com`
5. install Dory: https://github.com/FreedomBen/dory `brew install dory`
6. Copy .dory.yml file from Slack into your home folder
7. `docker compose build`
8. `dory up`
9. `docker-compose -f docker-compose.yml up -d`

Then to take it down:
1. `docker-compose -f docker-compose.yml down`
2. `dory down`

**Comment by phil-plencner-hl** [comment]
Here is the `.dory.yml` file so you don't have to dig through the Slack:
https://harvard-huit.slack.com/archives/C02LLJDGQ9Z/p1650054577513289

**Comment by enriquediaz** [comment]
This is done.
