### ISSUE TITLE
EPIC - Update View Files

### ISSUE THREAD

**Issue by crisr15** [harvard-lts/CURIOSity#10]
# Summary

The design and views from the current Curiosity app need to be transferred to the new application.  A gem is available to bring in the assets.  Additionally, we will want to look at the included tickets and address changes as necessary.  

Gem: https://gitlab.com/harvard-library-web-team/harvard-patterns-gem

Tickets included: 
#32 
#33 
#27 
#31 
#23 

Ticket 31 may be removed from this and listed separately if not related to how the components are being viewed and is instead related to how they are harvested.

Link to Enrique's mockups: https://www.sketch.com/s/39eb3859-75e8-4add-8498-6cbf2934d73c/a/25a1d2e

**Comment by phil-plencner-hl** [comment]
to install the gem, you can put this in your gemfile:
`gem 'harvard-patterns-gem', '1.1', :git => 'https://gitlab.com/harvard-library-web-team/harvard-patterns-gem.git', :tag => '1.1'`

**Comment by mferrarini** [comment]
looking at this file might also be helpful for overriding parts of vanilla bootstrap: https://github.com/harvard-huit/Harvard-Geospatial-Library/blob/main/app/assets/stylesheets/_harvard-bootstrap.scss

**Comment by summer-cook** [comment]
Hi! I'm working on this ticket but not able to assign myself to it. Can someone either assign me or give me permissions to assign myself?

**Comment by orangewolf** [comment]
We think all the parts of this epic that are part of the 3.0 launch are done. @enriquediaz do you want to close this epic even though parts of #23 and parts of #31 have are still open (but have been moved out of the 3.0 launch milestone)?

**Comment by enriquediaz** [comment]
Sounds good, @orangewolf. I've created a "Future Enhancements" label for work we'll tackle post-launch, assigned it to these two issues, and removed any SoftServ assignees from them.

**Comment by VanessaVenti** [comment]
@dl-maura and @phil-plencner-hl can you test/confirm this one is done?

**Comment by dl-maura** [comment]
https://github.com/harvard-lts/CURIOSity/issues/32
https://github.com/harvard-lts/CURIOSity/issues/33
https://github.com/harvard-lts/CURIOSity/issues/23

The above are done, there are 2 tickets that aren't but would spawn their own tickets (one is a future enhancement, and one is post-accessibility audit):
https://github.com/harvard-lts/CURIOSity/issues/27
https://github.com/harvard-lts/CURIOSity/issues/31

So we will close this and just monitor those tickets on their own
