### ISSUE TITLE
[3] OAI Mapping File Upload Form

### ISSUE THREAD

**Issue by summer-cook** [harvard-lts/CURIOSity#104]
# Summary
UI changes related to harvesting

# Issues
1. "We uploaded the mapping file but it doesn't indicate it was uploaded, still just says browse for file"
    - the field for uploading the file needs to change when you select it
    To reproduce:
    - in top menu go to Exhibit Dashboard
    - go to Items page
    - click Add Items
    - fill in OAI fields (see pin in slack), select New Mapping in Custom Mapping File

# Screenshot

![Image](https://user-images.githubusercontent.com/32469930/181800299-14724144-46ca-4fcb-8afc-bc331972779b.jpg)

# Notes 

The form for this lives in the harvesting gem: https://github.com/harvard-lts/spotlight-oaipmh-resources

**Comment by bkiahstroud** [comment]
2. The modal issues are likely due to custom styles, possibly coming from the Harvard Patterns Gem

**Comment by labradford** [comment]
https://github.com/harvard-lts/spotlight-oaipmh-resources/blob/main/app/views/spotlight/resources/oaipmh_harvester/_form.html.erb

**Comment by kirkkwang** [comment]
known [issue](https://github.com/bootstrap-ruby/bootstrap_form/issues/528
) with Bootstrap Form

[this](https://github.com/bootstrap-ruby/bootstrap_form/issues/528#issuecomment-533764879) solution seems to work

**Comment by VanessaVenti** [comment]
Looks good on QA!
