### ISSUE TITLE
Broken Diacritics

### ISSUE THREAD

**Issue by summer-cook** [harvard-lts/CURIOSity#106]
# Summary
Diacritics are either not displaying correctly in the UI, or not saving correctly in the backend when these values are harvested

![Image](https://user-images.githubusercontent.com/73361970/181386110-db5172f8-fabe-4a8b-9b5e-567ab27a25e1.jpg)

# Acceptance Criteria
- [x] Diacritics are displaying correctly after harvest

**Comment by VanessaVenti** [comment]
Looks good on QA!
