### ISSUE TITLE
Multivalued Fields in Harvests

### ISSUE THREAD

**Issue by summer-cook** [harvard-lts/CURIOSity#107]
# Summary
We need to make sure multivalued fields are being harvested correctly

# More info
From Vanessa:
Since it looks like we are getting close to testing harvesting, I wanted to make sure it is on folks radar that there are a couple things we need set up to compare harvests from our existing exhibits to newly migrated ones.
The attached 2.0 template is what I use as the basis for all new exhibits that has all the fields set up to map to the [curiosity.yml](https://github.com/harvard-lts/spotlight-oaipmh-resources/blob/job_entry/harvard_yaml_mapping_files/mods/curiosity.yml). To be able to compare a harvest, this exhibit template either needs to be mapped to 3.0 OR manually recreated. I know 
[@Summer](https://assaydepot.slack.com/team/U02SG739U4U)
 and 
[@kiah](https://assaydepot.slack.com/team/U02S77SA0MC)
 were working on mapping 2.0 exhibits to 3.0, not sure where that left off.
In recreating the fields, I see there is now a new check box for Multi-valued fields that didn't exist in 2.0. I believe 
[@deedee](https://assaydepot.slack.com/team/UPG864HB8)
 came up with a fix for this separately for us before, so I'm not sure what needs to change to make things work in 3.0. Looking at the yaml, it looks likely that any fields with multivalue-breaks: "yes" needs this check box checked, but Dee Dee please do let us know if there another place we should be looking at to see which fields are multivalued and/or if we should consult Robin.

From DeeDee:

[@Vanessa Venti](https://assaydepot.slack.com/team/UPCNYG5K4)
 the Solr schema for 2.0 has all _tesim and _ssim fields as multiValued="true". Therefore when you build the yaml file and set multivalue-breaks: "yes" it treats each value as a facet. I haven't followed this closely enough to know how much the Solr schema has changed between 2.0 and 3.0 but the checkbox you are showing indicates that specific fields can ve set to multivalued now.  My hunch is that you would have to check both the checkbox and set the yaml mutivalue-breaks to replicate what we are doing in 2.0. However, this is just a guess.

# Acceptance Criteria
- [x] Multivalued fields pull in successfully

**Comment by sephirothkod** [comment]
#112 is actually the same issue and so it is a duplicate. We'll close #112 and just link it here.

**Comment by VanessaVenti** [comment]
Looks good on QA!
