### ISSUE TITLE
[5] Ability to search items by ID and Unique ID

### ISSUE THREAD

**Issue by summer-cook** [harvard-lts/CURIOSity#111]
## Summary

When searching for a specific record, it should be discoverable by ID and unique ID. Both must be indexed and searchable.

## Acceptance Criteria
- [x] As a user, I find an item by searching for its ID
- [x] As a user, I find an item by searching for its unique ID

## Notes 
Unique ID is `#{Exhibit ID}-#{Item ID}`

Items in the UI are `Spotlight::Resource::OaipmhUpload` in the Rails models

### Possible Steps

- If this is an indexing issue, add it to the `OaipmhUpload#to_solr` method
- If this is already indexed, look in the catalog controller to see if it is a field we search against

### Examples 

[This item](https://curiosity.lib.harvard.edu/contagion/catalog/36-990006049270203941_RADSCHL:1267673) is searchable by both methods: 

- ID: https://curiosity.lib.harvard.edu/contagion/catalog?utf8=%E2%9C%93&exhibit_id=contagion&search_field=all_fields&q=990006049270203941_RAD.SCHL%3A1267673 
- Unique ID: https://curiosity.lib.harvard.edu/contagion/catalog?utf8=%E2%9C%93&exhibit_id=contagion&search_field=all_fields&q=contagion-990006049270203941_RAD.SCHL%3A1267673

**Comment by kirkkwang** [comment]
Fixed with https://gitlab.com/notch8/harvard-curiosity/-/merge_requests/97, however adding to it a bit more, where the user can just copy paste from url (which is the Unique ID) and omit the Exhibit ID and still be able to search

**Comment by VanessaVenti** [comment]
Looks good on QA!
