### ISSUE TITLE
UI item display tweaks

### ISSUE THREAD

**Issue by summer-cook** [harvard-lts/CURIOSity#112]
[From slack](https://assaydepot.slack.com/archives/C02LLJDGQ9Z/p1658955524969019)
```Need some UI tweaks from harvesting in item display(see: how subjects is one each line)```

![Image](https://user-images.githubusercontent.com/73361970/181387865-5e7227a2-cfb3-4de3-bb25-dde2dbf49faa.jpg)

**Comment by summer-cook** [comment]
@dl-maura hi! we need a little more clarification on this one. Do you mean that you want the subjects each be on their own individual line?

Also, are there any other tweaks needed to how they are displayed? Feel free to edit this ticket directly if thats easier, i just wasn't totally sure about this one from your post. Thank you!

**Comment by dl-maura** [comment]
@VanessaVenti I'm deferring to you on this, I know you pointed out the subjects as an issue but I don't want to speak for correct behaviors/what you want to see

**Comment by VanessaVenti** [comment]
Hi @summer-cook - Yes, any multi-valued field (like subjects) should be broken out on it's own line. We also hyperlink any links that appear in the metadata. I think that might be the only other thing we noticed so far that we forgot to mention. I'm sure there will be more things as we dive in deeper, but this is what stood out so far.

Here is a screenshot of a current record as an example:
![Screen Shot 2022-07-28 at 9 02 43 AM](https://user-images.githubusercontent.com/60190174/181512047-45b32c9b-a8a8-4b0f-a925-8d636d8dec91.png)
