### ISSUE TITLE
Harvest status tracking - post update every 50-100 records

### ISSUE THREAD

**Issue by bkiahstroud** [harvard-lts/CURIOSity#113]
## Summary

>The other thing that stands out is because it is showing the status of 10 records at a time that list is going to get very long for a lot of jobs. Most collections have somewhere between 2-4K items, but our largest one has over 10K items. I wonder if grouping them in chunks of 50 or 100 might be better?

![Curation - Dashboard dev - Harvard Curiosity 2022-07-21 at 10 51 26 AM](https://user-images.githubusercontent.com/32469930/181585341-9cf58141-af4b-41cc-9d08-224bf3d54289.jpg)

**Comment by summer-cook** [comment]
## Passed Notch8 QA

Processing is now shown in sets of 100


![Image](https://user-images.githubusercontent.com/73361970/183204993-3653bb1b-66d3-4c37-907a-d3d5b65c0622.png)

**Comment by VanessaVenti** [comment]
Looks good in QA!
