### ISSUE TITLE
[3] Modal Styles are incorrect

### ISSUE THREAD

**Issue by orangewolf** [harvard-lts/CURIOSity#115]
Modal UI needs to be updated 

![Image](https://user-images.githubusercontent.com/73361970/181385723-ce5c6e8d-ae0e-4ec8-ab08-81e43e617f7b.jpg)

This appears to be all modals, but a specific example is found by the following

In an Exhibit that has harvested items
- click Exhibit Dashboard in upper right menu
- under Recent activity, click the status

## Acceptance Criteria
- [x] Title should not run off the right side of the modal
  - The harvester has the best name to test this with (`Spotlight::Resources::PerformHarvestJob`) 
- [x] X to close modal should be visible
- [x] Details column has `{` and `}` that should not show

## Notes

The modal issues are likely due to custom styles, possibly coming from the [Harvard Patterns Gem](https://gitlab.com/harvard-library-web-team/harvard-patterns-gem). Overrides should be made in the local app (not the gem)

**Comment by labradford** [comment]
width is set in this style rule:
```
@media (min-width: 992px)
  .modal-lg, .modal-xl {
    max-width: 800px;
}
```
changing max-width to a percentage (for me 52% worked well) might be a solution

**Comment by labradford** [comment]
For the `{}` tags, this style rule might work:
```
#blacklight-modal .modal-body pre {
    display: none;
}
```

**Comment by labradford** [comment]
https://gitlab.com/notch8/harvard-curiosity/-/merge_requests/96

**Comment by summer-cook** [comment]
#### Passed Notch8 QA

Staging: beautifully responsive modal



![Image](https://user-images.githubusercontent.com/73361970/183201826-506cc3c9-fa5c-47b7-89af-1216866010f8.png)

**Comment by VanessaVenti** [comment]
Looks good on QA!
