### ISSUE TITLE
Importing Exhibits that have Harvesters throw errors

### ISSUE THREAD

**Issue by bkiahstroud** [harvard-lts/CURIOSity#116]
## Summary

Some exported Exhibit JSON files from the old app try to import `Spotlight::Resources::Harvester` resources. 

<details><summary>Example (demo-export.json)</summary>

```json
  "resources": [
    {
      "type": "Spotlight::Resources::Harvester",
      "url": "https://api.lib.harvard.edu/oai/",
      "data": {
        "base_url": "https://api.lib.harvard.edu/oai/",
        "set": "demo",
        "mapping_file": "curiosity.yml",
        "job_entry": {
          "id": 278,
          "start_time": "2019-03-07 15:18:49 UTC",
          "job_status": "in_progress",
          "exhibit_id": 47,
          "job_item_count": 0,
          "job_items_estimate": null,
          "end_time": null,
          "user_id": 11594692,
          "created_at": "2019-03-07 15:18:44 UTC",
          "updated_at": "2019-03-07 15:18:49 UTC",
          "job_type": "Harvesting"
        },
        "type": "MODS",
        "user": {
          "id": 11594692,
          "email": "szatsky@fas.harvard.edu",
          "created_at": "2019-02-25 21:15:16 UTC",
          "updated_at": "2019-02-28 18:18:49 UTC",
          "guest": false
        },
        "cursor": null,
        "count": 0,
        "failed_items": null
      },
      "created_at": "2019-03-07T15:18:49.000Z",
      "updated_at": "2019-03-07T15:18:49.000Z"
    },
    ...
```

</details>

`Spotlight::Resources::Harvester` no longer exists; it has been replaced by `Spotlight::OaipmhHarvester`. There are several relevant differences between the two: 

- `Spotlight::OaipmhHarvester` is not a `Resource` and thus should no longer be nested under `"resources"` in the JSON 
- `Spotlight::OaipmhHarvester` does not have a `:data` attribute that contains a hash. Instead, the harvester model has top-level attributes like `:base_url` and `:set` that values from `:data` belong in 
- The `"job_entry"` sub-hash refers to a model that no longer exists 
  - I think incoming data related to `"job_entry"` can probably just be dropped; needs confirmation 

Ideally, the importing logic (`ExhibitImportExportServiceDecorator#from_hash!`) will be updated to account for these differences (similar to [this MR](https://gitlab.com/notch8/harvard-curiosity/-/merge_requests/94)). 

## Acceptance Criteria

- [x] Importing Exhibit JSON files that contain `Spotlight::Resources::Harvester` resources will create a `Spotlight::OaipmhHarvester`s instead
- [x] Each `Spotlight::OaipmhHarvester` created will persist the following data: 
  - [x] `base_url`
  - [x] `set`
  - [x] `mapping_file`
  - [x] `type` (nested under `data`, e.g. `"MODS"` not `"Spotlight::Resources::Harvester"`)
  - [x] `user_id`

## Testing Instructions 

<details><summary>For developers:</summary>

1. Download one of the files in [this folder](https://drive.google.com/drive/u/0/folders/1SlOpuzlmPMWl1Mh-dedMPJQclkv_yCEt) (ensure it has `Spotlight::Resources::Harvester`s under `"resources"`) 
2. Login as an admin 
3. Create a new Exhibit 
4. Navigate to Exhibit Dashboard > General > Import Data
5. Click "Browse" and select the JSON file
6. Click "Import Data"
7. After the import succeeds, open a rails console in the web container (`docker compose exec web bin/rails c`)
8. Ensure a `Spotlight::OaipmhHarvester` that meets the Acceptance Criteria was created for each harvester listed in the JSON file 
9. For each `Spotlight::OaipmhHarvester`, trigger the harvest<sup>1</sup>
10. Validate the the harvest runs successfully 

<sup>1</sup> See dropdown

<details><summary>Dropdown</summary>

```ruby
Spotlight::Resources::PerformHarvestJob.perform_later(harvester: <harvester instance>)
```

</details>

</details>

<details><summary>For non-developers:</summary>

1. Download one of the files in [this folder](https://drive.google.com/drive/u/0/folders/1SlOpuzlmPMWl1Mh-dedMPJQclkv_yCEt) (ensure it has `Spotlight::Resources::Harvester`s under `"resources"`) 
2. Login as an admin 
3. Create a new Exhibit 
4. Navigate to Exhibit Dashboard > General > Import Data
5. Click "Browse" and select the JSON file
6. Click "Import Data"
7. No errors should be thrown 

</details>

## Additional Context

As part of upgrading the [spotlight-oaipmh-resources](https://github.com/harvard-lts/spotlight-oaipmh-resources) gem to be compatible with Spotlight 3.3.0, we converted `Spotlight::Resources::OaipmhHarvester` into `Spotlight::OaipmhHarvester` (see [this PR](https://github.com/harvard-lts/spotlight-oaipmh-resources/pull/9)).

**Comment by alishaevn** [comment]
picking up this ticket!

**Comment by kirkkwang** [comment]
using `metadata_type` instead of using `type`

**Comment by kirkkwang** [comment]
`OaipmhHarvester`s were successfully created with the `base_url`, `set`, `mapping_file`, `metadata_type`, and `user_id`.

![image](https://user-images.githubusercontent.com/19597776/182669053-913b3b0b-21b7-4efd-9299-b862b15557f5.png)

However, when running the job with:
```ruby
Spotlight::Resources::PerformHarvestsJob.perform_now(harvester: Spotlight::OaipmhHarvester.last)
```
is failing

![image](https://user-images.githubusercontent.com/19597776/182671776-d702fc4f-5cdf-4186-965a-973f051045ce.png)

**Comment by kirkkwang** [comment]
Errors were occurring on my dev environment but not @sephirothkod's, I think I just had something weird going on...

**Comment by kirkkwang** [comment]
Currently on staging, getting permissions error
```shell
App 975 output: [151b809ef98a05310baa9b0e9d27a27f] Errno::EACCES (Permission denied @ dir_s_mkdir - /app/spotlight/public/uploads/tmp/1659736685-413731957705518-0001-6128):
```

**Comment by crisr15** [comment]
This should be unblocked now.

**Comment by bkiahstroud** [comment]
I'm still seeing a permissions error on staging

**Comment by bkiahstroud** [comment]
The staging permissions error has been resolved

**Comment by bkiahstroud** [comment]
Kirk's observed error [here](https://github.com/harvard-lts/CURIOSity/issues/116#issuecomment-1204264752) was the result of missing mapping files. It is fixed in [this MR](https://gitlab.com/notch8/harvard-curiosity/-/merge_requests/140).

**Comment by summer-cook** [comment]
@bkiahstroud I am trying to test this on staging, but the testing instructions require opening a rails console in the web container to see if there are harvesters. I think they were written with testing in dev in mind, not staging. is there another way to see if harvesters imported successfully? Do I need to look in rancher?

(regardless, if there is a non console way to check that would be better to make it easier for harvards team to test as well)

**Comment by bkiahstroud** [comment]
@summer-cook This ticket is one of those ones that's hard to verify as a non-developer. I just added a "non-developer" section to the testing instructions for when Vanessa is looking at this later. 

For the developer testing instructions, yes, for our staging QA it needs to be verified in rancher

**Comment by VanessaVenti** [comment]
I just test this in Harvard QA and got the following error:
![Image](https://user-images.githubusercontent.com/60190174/188909891-533d4d00-b2fc-4ef0-861b-5684621e63be.png)

@phil-plencner-hl and @dl-maura did this work for you?

**Comment by dl-maura** [comment]
I responded to Vanessa in slack, this is actually correct -- can't reuse exhibit IDs
