### ISSUE TITLE
Admins can see curator or logged out user views.

### ISSUE THREAD

**Issue by crisr15** [harvard-lts/CURIOSity#12]
# Summary

Be able to see curator or logged out users views from within the admin account. This may mean bringing masked roles over or it may be a clean implementation in a more Rails standard way (such as become feature).

### User Role Masks
User role masks are available for site admins only to use: 1) during training so they can present with the curator role mask while being logged in as an admin and 2) for testing curator/exhibit admin permissions.

Masks are applied/cleared by going to the following URLs:
- To enable curator mask: https://curiosity.lib.harvard.edu/admin_users/mask_role/curator
- To enable exhibit admin mask: https://curiosity.lib.harvard.edu/admin_users/mask_role/admin (Note: This is to see the admin role when logged in as a super admin.)
- To clear a mask: https://curiosity.lib.harvard.edu/admin_users/clear_mask_role (Note: To switch between curator and exhibit admin masks, you must first clear the mask.)

There is now a Viewer role in 3.0, should we create a Viewer mask?

[Here is a screencast](https://harvard.zoom.us/rec/share/P-rD_WvXp2xptUURcAIRc_n-epa_gxTVl63wic5tZswLbovbkxEszXWhTv-_WLI.1jW_zTNUwCiIiugN) of what using these roles looks like in our production instance.

**Comment by summer-cook** [comment]
@VanessaVenti Thank you! I created a separate ticket to move items in the admin view: https://github.com/orgs/harvard-lts/projects/4/views/1 and I added a link to your comment above so that when i pick it up i can check if it makes sense to look at any of the other tasks in the admin dashboard ticket.

**Comment by VanessaVenti** [comment]
Looks good on QA!
