### ISSUE TITLE
Add the set_name to exhibit

### ISSUE THREAD

**Issue by summer-cook** [harvard-lts/CURIOSity#122]
# Summary

at the exhibit level, among its basic settings, we talked about how there can be a new field there where a curator can provide the name  of the full-text set, and that field value could be passed through as the “set” parameter value for when a user wishes to search the full text of an exhibit.

# Testing Instructions

1. sign in
2. go to an existing exhibit or create a new exhibit
3. go to the exhibit dashboard
4. click on the "general" link in the sidebar to go to the general settings page
5. check that as a user, you are able to add a set name to an exhibit
6. save the exhibit and make sure the set name persists

you should see the field in the exhibit edit form 

![Screen_Shot_2022-08-05_at_9 10 51_AM](https://user-images.githubusercontent.com/73361970/183743569-c6f8dc70-67f7-4b58-be37-c02afdedbb6e.png)

**Comment by crisr15** [comment]
@summer-cook Can you link the MR on this ticket

**Comment by summer-cook** [comment]
yes! https://gitlab.com/notch8/harvard-curiosity/-/merge_requests/114

**Comment by VanessaVenti** [comment]
@summer-cook can you rename Set Name to FTS Set Name to distinguish it from the LibraryCloud set name? I added this as a task in [#83](https://github.com/harvard-lts/CURIOSity/issues/83) but I'm wondering if it should be done as part of this story instead before closing this one out. Let me know what you think is best.

**Comment by bkiahstroud** [comment]
@VanessaVenti we can definitely do this

**Comment by bkiahstroud** [comment]
Second MR: https://gitlab.com/notch8/harvard-curiosity/-/merge_requests/148

**Comment by dl-maura** [comment]
This is set, should get to our QA today

![Image](https://user-images.githubusercontent.com/61880785/188662700-5f71d41a-4536-4018-b05f-f7ff222e121e.png)

**Comment by VanessaVenti** [comment]
Looks good on QA!
