### ISSUE TITLE
Test the API/figure out what the call needs to be for FTS and get responses

### ISSUE THREAD

**Issue by summer-cook** [harvard-lts/CURIOSity#123]
- JSON is not working in API

**Comment by kirkkwang** [comment]
JSON example:

`curl "https://fts.lib.harvard.edu:8443/fts/api/v2/search?S=curiosity_contagion&Q=hospital&L=1984&U=2000&B=1-20&F=J" > json_example.json`

**Comment by bkiahstroud** [comment]
Closing since we're now using a Solr proxy instead of the API
