### ISSUE TITLE
Fix "Copy Manifest Link"

### ISSUE THREAD

**Issue by summer-cook** [harvard-lts/CURIOSity#125]
The copy manifest link should point to the actual iiif manifest and not the spotlight manifest- it is currently pointing to the wrong place (and the spotlight manifest doesn't work with this ID anyways, it would need the spotlight ID)

![Image](https://user-images.githubusercontent.com/73361970/183139773-893f1feb-655d-47d1-aef3-8cefa471b622.png)

**Comment by bkiahstroud** [comment]
MR in GitLab: https://gitlab.com/notch8/harvard-curiosity/-/merge_requests/120

**Comment by VanessaVenti** [comment]
Looks good on QA!
