### ISSUE TITLE
Handle works with long titles for masonry results view

### ISSUE THREAD

**Issue by summer-cook** [harvard-lts/CURIOSity#129]
We noticed that works with extra long titles will extend way past the thumbnail in the masonry search results view:

![Image](https://user-images.githubusercontent.com/73361970/183216334-c821fbf6-85d1-41a7-b65c-6bc74924f3b3.gif)

**Comment by summer-cook** [comment]
@VanessaVenti there are a couple ways we can deal with this-

1. truncate the titles
2.  increase the width of the images in the masonry view only
3. make the titles into a tooltip type thing?

let me know if you think any of these would be best. I don't know if this needs a 3.0 launch label, since not every exhibit has masonry view but if you think it needs one feel free to add

**Comment by enriquediaz** [comment]
Hi @summer-cook: @VanessaVenti and I spoke and we agree that, as a baseline, the titles should truncate. Please have titles truncate (that is, insert an ellipsis) after 75 characters are displayed, not counting blank spaces as characters. Thank you for raising this!

**Comment by mferrarini** [comment]
These issues have been addressed in the [most recent merge to main](https://github.com/harvard-lts/CURIOSity/pull/221) and tracked in another ticket. Closing.
