### ISSUE TITLE
Create urn_ssi field

### ISSUE THREAD

**Issue by bkiahstroud** [harvard-lts/CURIOSity#130]
## Acceptance Criteria

- [ ] Create a `urn_ssi` field in CURIOSity
- [ ] Modify [spotlight-oaipmh-resources](https://github.com/harvard-lts/spotlight-oaipmh-resources) to fill that field based on the ~`full_image_url`~ **`full_image_url` is not correct, need to figure out which one is correct**

**Comment by crisr15** [comment]
Don't use URN as sometimes it will be wrong (page URN instead of book URN).  Use objectID instead.

**Comment by bkiahstroud** [comment]
@sephirothkod this is merged and ready for QA as of https://gitlab.com/notch8/harvard-curiosity/-/merge_requests/118, correct?

**Comment by bkiahstroud** [comment]
We ended up using `urn_ssi` after all, not `object_id_ssi`

**Comment by summer-cook** [comment]
How can this be tested?

**Comment by bkiahstroud** [comment]
@summer-cook yes, that is the `urn_ssi` field/data

**Comment by dl-maura** [comment]
We have this in our qa, closing!
