### ISSUE TITLE
[1] Fix metadata names in en.yml

### ISSUE THREAD

**Issue by summer-cook** [harvard-lts/CURIOSity#134]
# Summary

Ideally, it would be great to not have to rename the fields after harvesting - is it possible to set the display label how I rename it after harvesting and configure it to work with the yaml on the backend (named with the preharvesting labels)?

[2.0 Metadata Template.xlsx](https://docs.google.com/spreadsheets/d/1ku4jp73zvvFLSJt0j80h53g3Z7SThn-3rcFOPLpesk8/edit#gid=0)

# Acceptance Criteria

- [ ] metadata fields are displayed how they are ultimately named after harvesting (check that this is consistent with the Metadata Template above

**Comment by summer-cook** [comment]
### Notch8 QA- not passed

These are the issues I find with this ticket. I'm not sure if changes are missing from staging, or what we are responsible for changing but this is where the names of the fields in the UI differ from their template above.

- There are still 2 Attribution fields
- Dates and Creation Dates still exist even though they only want Date, both are still plural even though they want singular
- Places of Origin, Publishers, Languages, Genres, Digital Formats, Cultures, are plural even though they want singular
- Note should be plural, not singular
- Style Periods should be Style / Periods
- Materials Techniques should be Materials / Techniques
- There is no "Repository" but there is a "Harvard Repository"
- There is no "Rights"
- Record Id should be Record ID
- Hollis Record should be HOLLIS Record
- There is no "Permalink Ham" OR what it should be which is Harvard Art Museums
- Exhibit tags is still "exhibit tags" and should be "Curator Tags"
- There is no "Collection" only "In Collection" which is a separate field
- There is no "Finding Aid" only "Finding Aid Component" which is a separate field
- There is no Permalink dcp- but there ARE Permalink Channing and Permalink Horblit

**Comment by jeremyf** [comment]
There's "self-help" instructions on https://github.com/harvard-lts/CURIOSity/issues/147 to see if these are problems that the Harvard team can resolve.

**Comment by bkiahstroud** [comment]
The following of [the above](https://github.com/harvard-lts/CURIOSity/issues/134#issuecomment-1231885907) have been resolved: 

- There is no "Repository" but there is a "Harvard Repository"
- There is no "Rights" (added [here](https://gitlab.com/notch8/harvard-curiosity/-/merge_requests/156))
- There is no "Permalink Ham" OR what it should be which is Harvard Art Museums
- There is no "Collection" only "In Collection" which is a separate field
- There is no "Finding Aid" only "Finding Aid Component" which is a separate field
- There is no Permalink dcp- but there ARE Permalink Channing and Permalink Horblit

**Comment by bkiahstroud** [comment]
Closing this in favor or tracking it on #136
