### ISSUE TITLE
[1] Address duplicate fields

### ISSUE THREAD

**Issue by summer-cook** [harvard-lts/CURIOSity#135]
# Summary
Remove any duplicate fields

"I see there are lots of extra fields and some missing ones set as the current defaults in 3.0. We also don't need fields to be both tesim and ssim; Creator/Contributor and Creators/Contributors is the one exception where we have both and use them for different purposes."

**Comment by summer-cook** [comment]
I think this is blocked from QAing fully until 

#155 Conflicting fields cause metadata not to render in UI  

passes QA

**Comment by bkiahstroud** [comment]
MR: https://gitlab.com/notch8/harvard-curiosity/-/merge_requests/160

**Comment by bkiahstroud** [comment]
The ticket description mentions that fields don't need to be "both tesim and ssim" (excluding the Creator/Contributor fields), but I've left those for now for a couple reasons: 

1. Several places reference both forms of the fields 
  a) [curiosity.yml mapping file](https://github.com/harvard-lts/spotlight-oaipmh-resources/blob/job_entry/harvard_yaml_mapping_files/mods/curiosity.yml) (e.g. `subjects_ssim` and `subjects_tesim`) 
  b) [demo-export.json](https://drive.google.com/file/d/1dSeBza_TKPRZZigxloL7x8FiGD_Q2njx/view?usp=sharing) (all fields under `facet_fields` are `_ssim` while several under `index_fields` are `_tesim`) 
2. It isn't clear which should be ssim and which should be tesim on a field-by-field level

**Comment by bkiahstroud** [comment]
PR: https://github.com/harvard-lts/CURIOSity/pull/187

**Comment by bkiahstroud** [comment]
Closing this in favor or tracking it on #136
