### ISSUE TITLE
Broken thumbnails when harvesting

### ISSUE THREAD

**Issue by bkiahstroud** [harvard-lts/CURIOSity#137]
## Summary

Upon harvesting the demo set to [https://curiosity-qa.lib.harvard.edu/spotlight/import-exhibit-test](https://curiosity-qa.lib.harvard.edu/spotlight/import-exhibit-test/catalog?exhibit_id=import-exhibit-test&search_field=all_fields&q=) many items are missing thumbnails:

<details><summary>Screenshot</summary>

![Image](https://user-images.githubusercontent.com/32469930/184037868-f0ed9032-2eb5-4df4-9130-a8b5ae12470a.jpg)

</details>

## Acceptance Criteria

- [x] All thumbnails show up after harvesting

## Notes

When comparing the image sources of thumbnails that are working vs. thumbnails that aren't: 

```sh
# Broken
https://ids.lib.harvard.edu/ids/iiif/8282876/full/,150/0/default.jpg/full/300,/0/native.jpg

# Working
https://ids.lib.harvard.edu/ids/iiif/1667094/full/300,/0/native.jpg
```

At some point when parsing harvested data, an extra `/full/,150/0/default.jpg` gets added to the middle of the URL that shouldn't be there. This points to the issue being caused by some broken regex somewhere.

**Comment by sephirothkod** [comment]
should be fixed in: https://github.com/harvard-lts/spotlight-oaipmh-resources/pull/23

**Comment by bkiahstroud** [comment]
Second PR: https://github.com/harvard-lts/spotlight-oaipmh-resources/pull/27

**Comment by VanessaVenti** [comment]
Looks good on QA!
