### ISSUE TITLE
Links in metadata are not hyperlinked

### ISSUE THREAD

**Issue by bkiahstroud** [harvard-lts/CURIOSity#139]
## Summary

![Image](https://user-images.githubusercontent.com/32469930/184039443-a6749685-69b2-49a1-b51d-4678e72d63ad.jpg)

## Acceptance Criteria

- These fields will display as hyperlinks: 
  - [x] All permalink fields
  - [x] HOLLIS Record 
  - [x] Finding Aid 
  - [x] Finding Aid Component

Optional: 

>there could also be a hyperlink within other fields such as Notes ([see this record as an example](https://curiosity.lib.harvard.edu/contagion/catalog/36-990006033660203941_HMSCOUNT:1204550)) - getting these to work is less important than the ones above as we don't have this working currently for this case, but thought I would mention it in case there is a solution that works for all cases

## Notes

Braydon thinks this is / used to be controlled by a config option in the catalog controller. Should start there

**Comment by bkiahstroud** [comment]
@VanessaVenti which fields should display as hyperlinks?

**Comment by VanessaVenti** [comment]
@bkiahstroud - Ideally, any links in the metadata would be hyperlinks, but the fields that only contain links are:
- all the permalink fields - there is a unique one for every exhibit as well as one for DCP and HAM that get applied to all exhibits
- all the fields that link to catalog records - HOLLIS Record, Finding Aid, Finding Aid Component
- there could also be a hyperlink within other fields such as Notes ([see this record as an example](https://curiosity.lib.harvard.edu/contagion/catalog/36-990006033660203941_HMSCOUNT:1204550)) - getting these to work is less important than the ones above as we don't have this working currently for this case, but thought I would mention it in case there is a solution that works for all cases

**Comment by jeremyf** [comment]
Reading Notes: https://github.com/projectblacklight/blacklight/wiki/Configuration---Results-View#helper-method

Here's what we'll want to do to make those elements links.

**Comment by jeremyf** [comment]
Reading Notes: I have a "fix" that allows us to specify the fields we render as links; however it breaks things.  So I'm continuing to explore.

Attached is a screenshot demonstrating what happens when I follow the Blacklight documentation.  Namely the `_tesim` fields move to the top of the list.

<img width="1376" alt="Screen Shot 2022-08-12 at 10 08 20 AM" src="https://user-images.githubusercontent.com/2130/184371109-f93de48c-56c7-4de2-ada0-20f242215b00.png">

**Comment by dl-maura** [comment]
![Screen Shot 2022-08-15 at 10 04 03 AM](https://user-images.githubusercontent.com/61880785/184650301-dcf0bb54-cc9f-4665-b550-a9f1457c0cf6.png)

Have this running on my local and I do see hyperlinks now

**Comment by VanessaVenti** [comment]
Looks good in QA, will add the optional case of hyperlinking within fields that have additional text such as Notes to the backlog.
