### ISSUE TITLE
Full Text Search

### ISSUE THREAD

**Issue by crisr15** [harvard-lts/CURIOSity#14]
# Summary

Application currently only does full text search via the Mirador viewer plugin. This would replace that with full text search in the same Solr as other search objects. Full text could then be supported in both the search bar and in the IIIF viewer for a more uniform interface.
Complete design decisions are pending further meetings. Harvard also needs to anticipate using full text search on future applications, so we need to build a scalable and reusable solution.
An approach to search functionality also needs to be defined, with the options being discrete search results for metadata-based and full-text search, vs. integrated results.

### Next steps
- [ ] Conduct technical review of mock ups

### Mock ups
- [View online via Sketch Cloud](https://www.sketch.com/s/83a22487-2bee-4f2e-a416-18116150d32a/a/oY49w8D/play)
- [View JPG files or download Sketch file from Google Drive](https://drive.google.com/drive/folders/15Uroqu6NNjvlb41_ulKC6EMidHZFP43U?usp=sharing)

### UX research report
[Report on the UX Research](https://docs.google.com/document/d/1e0ZYVjqlACDdRy4_OKc4sPXRH5o_VV09d3qtJz6xOv0/edit)

# Testing Instructions

** for testing purposes we will use the contagion set

1. Create a new exhibit
2. Run a harvest of the "contagion" set. make sure it completes successfully
3. Go into dashboard -> general -> exhibit settings and add the corresponding set name which is "curiosity_contagion"
4. Save the set name
5. Go to the exhibit homepage
6. Run a regular search. test that the search still works
7. Check the box in the search bar for full text search. Run a search of a word you will likely find in the set (I was using "epidemic" for testing purposes)
8. Look at the results
9. Test that the link to each matching result opens the correct page of results in the FTS UI

**Comment by crisr15** [comment]
How is the snipet of text selected on full text search items (its not a standard length, so we need to know what rules to use in order to select it). Can it be a set character limit?

What is the property that the full text search will be contained in?  

Does link take you to the highlighted text, or can it just load to the top of the document? Does it need to be able to highlight all the options.

**Comment by crisr15** [comment]
Link to FTS API documentation: https://drive.google.com/file/d/1NLSolV_SUx5eH2qZD056-M87AFP_Bh3s/view?usp=sharing

**Comment by crisr15** [comment]
Front End changes 
 - Add box for searching full text instead of solr query.  
 - view changes and results for full text search
 
Logic and Call related pieces
 - API call for full text search (probably pulling context and result text size)
 - Query solr for IDs passed back from the API.
 
After Mirador if possible
 - What happens when they click the search link to open the item?  Can we add the search subject into the iframe call?

**Comment by dl-maura** [comment]
We have bug tickets for the results errors, and the other parts of this were their own tickets
