### ISSUE TITLE
Hide Search Id and Unique Id in UI

### ISSUE THREAD

**Issue by summer-cook** [harvard-lts/CURIOSity#140]

**Comment by summer-cook** [comment]
@VanessaVenti I created this ticket in response to your feedback here:

> Search Id and Unique Id both appear to be pulling in the same info we have under Record ID - can those both be deleted?

Would it be okay if we hide them in the UI instead of deleting them? Then we will still have those fields saved in the db, but they will never show in the public view

**Comment by VanessaVenti** [comment]
@summer-cook - that's fine and actually I realized Search Id is slightly different where if there is a period in the ID it will strip it out as it does in the URL. For example with https://curiosity-qa.lib.harvard.edu/spotlight/import-exhibit-test/catalog/23-W387877_URN-3:HPREWARD:1182492 the Record ID and Unique ID is W387877_URN-3:HPRE.WARD:1182492, but the Search ID is W387877_URN-3:HPREWARD:1182492 so it's nice to be able to search both. For what is it is worth, I do think Unique ID and Record ID are the same though.

**Comment by enriquediaz** [comment]
Metadata is still being cleaned up but dashboard inspection confirms these two fields aren't visible.
