### ISSUE TITLE
[2] Sort order

### ISSUE THREAD

**Issue by bkiahstroud** [harvard-lts/CURIOSity#142]
## Summary

Under Search > Results we sort our fields by Relevance (relevancy score descending and id ascending) rather than just relevancy score descending because we found without the id ascending Spotlight would return the results in a different order every time a user conducted a search.

Originally reported [here](https://github.com/harvard-lts/CURIOSity/issues/132#issuecomment-1213218734) 

# Acceptance Criteria
- [ ] The search results return in the same order every time for the same query

**Comment by crisr15** [comment]
Lea Ann may have done work similar to this in the past and is a good resource.

**Comment by VanessaVenti** [comment]
Looks good on QA!
