### ISSUE TITLE
Exhibit Import - inconsistent attachment behavior

### ISSUE THREAD

**Issue by dl-maura** [harvard-lts/CURIOSity#144]
## Summary

>The behavior re: attachment import is inconsistent. Some attachments get imported on exhibit import but others (such as masthead) aren't importing as assets but coming in as url() links (see screenshot). These need to be brought in as downloaded files.

<details><summary>Archived description</summary>

We attempted an Exhibit Import but encountered numerous issues

- #146 :: Auto-increment does not adjust for our imported IDs in relevant tables. We want to reuse the IDs for the exhibits, attachments, etc. but errors happen after if you try to make a new exhibit that the ID is already in use. Auto-increment will beed to be adjusted after we finish exhibit import and table copies so this doesn't happen

- The behavior re: attachment import is inconsistent. Some attachments get imported on exhibit import but others (such as masthead) aren't importing as assets but coming in as url() links (see screenshot). These need to be brought in as downloaded files.

![Image](https://user-images.githubusercontent.com/61880785/184706375-767cc258-b8cb-4b26-944c-8ae874e36474.png)

- #145 :: subpage links are hardcoded so those aren't really working right. at least to fix it for prod we do need to edit the root path on spotlight/curiosity. our curiosity doesn't have the /spotlight so we need to eliminate that so the root is just curiosity.lib.harvard.edu

</details>

## Testing Instructions 

1. Add this line to your `.env` file: `APP_HOST=localhost:21407`
2. Start/restart your docker containers 
3. Login as an admin 
4. Create a new exhibit 
5. Navigate to Exhibit Dashboard > General > Import Data 
6. Import the demo exhibit 
7. Click on "Home" in the navbar 
8. Open the browser inspector tool and inspect images on the page 
9. Validate that the url points to `localhost:21407` (i.e. not `curiosity.lib.harvard.edu`) 

![CURIOSity Demo Site - Harvard Curiosity 2022-08-22 at 2 57 11 PM](https://user-images.githubusercontent.com/32469930/186025999-aaadeddc-eea5-4cb4-9a43-a58f374273e3.jpg)

**Comment by bkiahstroud** [comment]
@VanessaVenti are Exhibits the only records that have permalinks, a.k.a. should have their IDs from the old app brought over?

**Comment by VanessaVenti** [comment]
@bkiahstroud I'm not sure I'm totally following. It's the item records that have the permalinks, but they are based off of the Exhibit ID so for example the Slavery site has an exhibit ID of 74 so all the records in the that site have a 74 in the URL that the permalinks need to resolve to. For example: https://curiosity.lib.harvard.edu/slavery-abolition-emancipation-and-freedom/catalog/74-990000048030203941

Are you asking if there are other IDs that need to be brought over from the old system? If so, I'm not really sure. I think the only other thing is that the new exhibits know where the new copies of the uploaded imagery (like mastheads) live. But I know you and Maura are working on that.

**Comment by bkiahstroud** [comment]
After some investigation, I've discovered that the attachments that use URLs are coming from hard-coded values in the JSON. The masthead is one example (see `iiif_tilesource`): 

```json
  "masthead": {
    "type": "Spotlight::Masthead",
    "display": true,
    "source": "remote",
    "document_global_id": "",
    "created_at": "2018-12-12T18:36:02.000Z",
    "updated_at": "2019-07-23T13:08:28.000Z",
    "iiif_region": "582,579,1200,320",
    "iiif_manifest_url": "",
    "iiif_canvas_id": "",
    "iiif_image_id": "",
    "iiif_tilesource": "https://curiosity.lib.harvard.edu/images/551/info.json"
  },
```

**Comment by VanessaVenti** [comment]
@dl-maura this looks like one for you to test.

**Comment by dl-maura** [comment]
I THINK we're now at the point where this can be closed -- we know the answers to all the behavior questions, and Phil is going to be writing a script to do this. @phil-plencner-hl do you agree?

**Comment by dl-maura** [comment]
Phil said its ok to close!
