### ISSUE TITLE
Subpage links are hardcoded....

### ISSUE THREAD

**Issue by jeremyf** [harvard-lts/CURIOSity#145]
> subpage links are hardcoded so those aren't really working right. at least to fix it for prod we do need to edit the root path on spotlight/curiosity. our curiosity doesn't have the /spotlight so we need to eliminate that so the root is just curiosity.lib.harvard.

Derived from #144

**Comment by jeremyf** [comment]
Reading notes: this may be the result of mounting the spotlight engine at `/spotlight`, I'm investigating.

**Comment by bkiahstroud** [comment]
MR: https://gitlab.com/notch8/harvard-curiosity/-/merge_requests/132

**Comment by VanessaVenti** [comment]
@dl-maura - I think this one is for you to test, but let me know if I should also test it as well when exporting/importing is working.

**Comment by bkiahstroud** [comment]
The path we chose for this wasn't to try to un-hardcode the links, but rather to remove the `/spotlight` from the URL of the site so those links still work: 

```sh
# before
https://<base_url>/spotlight/<exhibit slug>

# after 
https://<base_url>/<exhibit slug>
```

**Comment by dl-maura** [comment]
This is set, closing
