### ISSUE TITLE
Auto-increment does not adjust for our imported IDs in relevant tables.

### ISSUE THREAD

**Issue by jeremyf** [harvard-lts/CURIOSity#146]
> Auto-increment does not adjust for our imported IDs in relevant tables. We want to reuse the IDs for the exhibits, attachments, etc. but errors happen after if you try to make a new exhibit that the ID is already in use. Auto-increment will beed to be adjusted after we finish exhibit import and table copies so this doesn't happen

Derived #144

**Comment by dl-maura** [comment]
Since we made a new ticket I am closing this one
