### ISSUE TITLE
Change thumbnail size to 600px and add documentation for how to do this

### ISSUE THREAD

**Issue by summer-cook** [harvard-lts/CURIOSity#148]
# How to change the item thumbnail size
1. go to the file `config/initializers/spotlight_initializer.rb`
2. change the setting for `config.featured_image_thumb_size` to whatever maximum dimensions you would like. the array in this setting represents the max width by the max height.

code:
https://gitlab.com/notch8/harvard-curiosity/-/merge_requests/133

**Comment by summer-cook** [comment]
@VanessaVenti hi Vanessa I just changed this and the update is in code review.

I also added the instructions for how to change this in the future to the description of the ticket as well as a link to the MR. i thought it might be something you guys would like to add to the harvard Wiki

**Comment by VanessaVenti** [comment]
Thanks @summer-cook! @dl-maura let me know when this is available on QA and I'll see how it looks.

**Comment by dl-maura** [comment]
This is on qa (confirmed the line in the container) but I also see demo as only being 300

**Comment by bkiahstroud** [comment]
Can you please attach a screenshot for: 

1. Where the correct dimension is being seen? 
2. Where the wrong dimension is being seen?

**Comment by summer-cook** [comment]
@bkiahstroud @dl-maura  i think I see what is going on with this. I will look at it this morning

**Comment by summer-cook** [comment]
After further investigation, I am wondering if we need to actually change something in the spotlight_oai_pmh gem to get this to work. The instructions above are how you would change the thumbnail size defaults for spotlight. When I manually upload an image, the correct larger size is displayed.
<img width="1200" alt="Screen Shot 2022-09-02 at 11 00 47 AM" src="https://user-images.githubusercontent.com/73361970/188177859-a4504463-8507-4a5f-9eba-118c6f8f4eba.png">

For some reason, the new size doesn't work for iiif images. I have noticed that when I create a slideshow widget and add an item to it, first it tries to use the new size but a portion of the url says undefined, and then it defaults back to the url that uses 300. 


[This is the line in spotlight](https://github.com/projectblacklight/spotlight/blob/b06511be2b93a1dd999aada2405ab8609592804f/app/models/spotlight/featured_image.rb#L38) where that URL gets created. 

this will require further investigation next week

**Comment by bkiahstroud** [comment]
@summer-cook When parsing the thumbnail during harvesting, we hard-code 300px dimension [here](https://github.com/harvard-lts/spotlight-oaipmh-resources/blob/main/app/models/spotlight/resources/oaipmh_mods_parser.rb#L189-L190). 

That's on me; I wasn't aware of the `Spotlight::Engine.config.featured_image_thumb_size` setting when making that change.

We could replace the hard-coded `300` with `Spotlight::Engine.config.featured_image_thumb_size[0]` to semi-dynamically grab the currently configured thumbnail size (`800`)?

**Comment by bkiahstroud** [comment]
Related PR: https://github.com/harvard-lts/spotlight-oaipmh-resources/pull/30

**Comment by phil-plencner-hl** [comment]
the spotlight-oaipmh-resources PR has been merged.
I have confirmed this is working locally and created a new tag/release and an accompanying MR in Gitlab using the new gem tag. (I also confirmed it is working over there):

- https://github.com/harvard-lts/spotlight-oaipmh-resources/releases/tag/v3.0.0-beta.5
- https://gitlab.com/notch8/harvard-curiosity/-/merge_requests/155

**Comment by dl-maura** [comment]
This is solved now going to close -- now that we changed the gem the documentation on changing thumbnail sizes is correct

**Comment by VanessaVenti** [comment]
Just noting that it was changed to 800px instead of 600px, I'll update the title too if I can. We'll look out for performance issues with this larger size.

**Comment by summer-cook** [comment]
@VanessaVenti sounds good. I think I ended up doing 800 since I was noticing some of them were still a tiny bit blurry in the slideshow view at 600. 800 was just enough to make them clear
