### ISSUE TITLE
Clearing FTS search term throws error

### ISSUE THREAD

**Issue by dl-maura** [harvard-lts/CURIOSity#153]
Tried searching full-text in a collection with a set, didn't get any results (which might be expected), but when I tried to clear the fts term I got an error. I do NOT have this happen when I clear a non-its search (search without checking search within)

Recording: https://drive.google.com/file/d/12csEmzNamwqEajpItmJlIAwiM-DhIVtz/view?usp=sharing

**Comment by dl-maura** [comment]
![Image](https://user-images.githubusercontent.com/61880785/185710567-70cd7b96-e22d-4ef1-97b0-00f653f3c0d0.png)

**Comment by bkiahstroud** [comment]
Not sure, but this might be fixed by [adding a set name to the exhibit](https://share.getcloudapp.com/Kou10ov2). Even if it is, we'll need to figure out how to not throw an error when performing a full text search on an exhibit that does not have a configured set name.

**Comment by dl-maura** [comment]
This one does have a set name

**Comment by VanessaVenti** [comment]
@dl-maura can you test this one? I'm not sure if there is something I should be looking for on the back end.

**Comment by dl-maura** [comment]
This is fixed, closing
