### ISSUE TITLE
Harvest allows submit when no set is named

### ISSUE THREAD

**Issue by dl-maura** [harvard-lts/CURIOSity#160]
If worker fails to harvest a collection (say due to a typo), it fails, but in the dashboard, it says it is 'successful' (see screenshots)

To recreate this problem, when doing an item harvest, misname the set (so Demo or dmeo instead of demo)

Screenshots:

<img width="1509" alt="Screen Shot 2022-08-23 at 3 12 50 PM" src="https://user-images.githubusercontent.com/13121501/186255661-6fcd70e6-da02-47a1-a2ec-7398733c6033.png">

<img width="1297" alt="Screen Shot 2022-08-23 at 3 13 58 PM" src="https://user-images.githubusercontent.com/13121501/186255699-15620c14-617d-410f-81f6-e21b3057b025.png">

## Testing Instructions 

1. Login as an admin 
2. Navigate to Exhibit Dashboard > Items > Add Items 
3. Without filling out any fields, click "Add MODS Items" 

Expected behavior: Form does not submit, telling the user that the field(s) are required

**Comment by bkiahstroud** [comment]
@VanessaVenti how does the old app handle this case? I can think of a couple ways to fix it, but figured being consistent with your previous system would be best

**Comment by VanessaVenti** [comment]
@bkiahstroud good question! Honestly I don't think the system handles this case very well currently. I think it keeps trying to harvest the job and I have to ask a dev to delete the job from the queue. Ideally, the system would see the setSpec doesn't exist and present me with an error message saying so, but I'm definitely open to hearing your ideas!

**Comment by bkiahstroud** [comment]
PR: https://github.com/harvard-lts/spotlight-oaipmh-resources/pull/28

**Comment by dl-maura** [comment]
That fix will prevent us from harvesting a blank, the second case is when a set name is wrong (so it isn't blank, I just have a typo or use an old name). We also get that successful even though it fails but also it seems like it stays open? The count on this one just keeps increasing.

![Image](https://user-images.githubusercontent.com/61880785/186528226-07a18fdc-f9ae-4120-a2cb-5e793e4ec7e9.png)

**Comment by bkiahstroud** [comment]
@dl-maura I split this ^ bug into its own ticket: https://github.com/harvard-lts/CURIOSity/issues/164

**Comment by dl-maura** [comment]
Sicne we're breaking this out into smaller tickets I've renamed this and am closing this one
