### ISSUE TITLE
Provision "beta" production environment

### ISSUE THREAD

**Issue by enriquediaz** [harvard-lts/CURIOSity#163]
Coordinate or complete the tasks for setting up a pre-production environment for CURIOSity 3.0 that will serve as its production instance when we're ready to switch over from the current implementation. This will clear the way to begin importing exhibits once the process has been finalized.

- [x] create Solr/Postgres/Redits instances (ops ticket)
- [x] confirm LastPass folder is up to date
- [x] initial deploy
- [x] request beta.curiosity.lib.harvard.edu
- [x] provision load balancer instance for CURIOSity
- [x] create initial administrative account in CURIOSity
- [x] have admins login and give them permissions

**Comment by enriquediaz** [comment]
@dl-maura please revise or add items to the checklist in the description above that I haven't accounted for in my initial pass.

**Comment by dl-maura** [comment]
@enriquediaz edited/added some things. ticket with ops is in already

**Comment by dl-maura** [comment]
The last pass folder has beta values so I think it is set for now (we do update things so we would just update on deploys as needed)
