### ISSUE TITLE
BUG: After Exhibit Import Process, harvesting duplicates items across collections

### ISSUE THREAD

**Issue by dl-maura** [harvard-lts/CURIOSity#165]
Demonstrated for Kiah, but when we do the exhibit import process, and then try to harvest items, the items harvested in one collection show up in all collections. There aren't duplicate solr or db entries, why this is happening is a mystery

**Comment by dl-maura** [comment]
How to Recreate for SoftServ:

I've confirmed this happens without the table and item import stuff that only Harvard is doing (since you don't have our db).

1.  Ideally, clear out everything (I always do a docker system prune and a docker volume prune) -- I don't know that you have to but it removes any other data that could cause issues
2. Get rid of tour APP_HOST variable so the exhibit import just references the live site.
3. Rebuild your container stack
4. Once the site is back, create your at least 2 collections that you have exhibit imports for (I always do demo and contagion but you can choose others if you'e working with them)
5. Once they're created do the exhibit import for each
6. Harvest items for ONE of the collections.

When it finishes you'll see those items also appear in the other collection's item list

**Comment by bkiahstroud** [comment]
>2. Get rid of tour APP_HOST variable so the exhibit import just references the live site.

@dl-maura why are we removing the `APP_HOST` variable?

**Comment by dl-maura** [comment]
my understanding was the code change you made will mean if APP_HOST is present the importer replaces with that, which then wont reference the prod site, it will try to reference something that doesn' exist and then it gets mad.
alternatively you could set it to the prod site /curiosity.lib.harvard.edu but this seemed easier

**Comment by dl-maura** [comment]
We have the workaround for this (exhibit import clears the filter field in the UI, doesn't seem to do this from the command line rake task), not sure if we want to try to fix the UI issue or is this actually expected/correct behavior from spotlight?

**Comment by VanessaVenti** [comment]
@dl-maura and @bkiahstroud - is there something I should test here? If so, can you provide instructions? thanks!

**Comment by bkiahstroud** [comment]
@VanessaVenti I think the next step for this ticket is answering the question "is the current state / workaround acceptable?". The "workaround" is a one-time step after importing exhibit data (for each exhibit) and is as follows: 

1. Login as an admin 
2. Create a new exhibit 
3. Import exhibit JSON data 
4. Navigate to Exhibit Dashboard > General > Filter items tab 
5. Fill out the form fields: 
  a) **Field:** spotlight_exhibit_slug_<exhibit_slug>_bsi (e.g. `spotlight_exhibit_slug_contagion_bsi`) 
  b) **Value:** true
6. Click Save Changes 
7. Harvest set

**Comment by bkiahstroud** [comment]
@dl-maura does that ^ sound right to you?

**Comment by VanessaVenti** [comment]
Hi @bkiahstroud - yes, that's totally fine.

**Comment by bkiahstroud** [comment]
Great! If you and @dl-maura agree then I think the only thing keeping this ticket from being closed is adding those instructions to documentation somewhere, just to make sure it gets captured.

**Comment by dl-maura** [comment]
Fine by me, I'll amend the steps here since I do things a bit different.

1. Login as an admin
2. Create a new exhibit
3. Navigate to Exhibit Dashboard > General > Filter items tab
4. Copy the filter that is present there
5. Import exhibit JSON data
6. Navigate to Exhibit Dashboard > General > Filter items tab
7. Fill out the form fields:
8. a) Field: spotlight_exhibit_slug_<exhibit_slug>_bsi (e.g. spotlight_exhibit_slug_contagion_bsi) (the thing you copied)
9. b) Value: true
10. Click Save Changes
11. Harvest set

I just find it easier to copy the pre-created filter so I don't worry about getting it wrong :-)
