### ISSUE TITLE
FTS - improved UX for when Exhibit Set Name is not set

### ISSUE THREAD

**Issue by bkiahstroud** [harvard-lts/CURIOSity#167]
## Summary

An exhibit’s set name is very important for FTS to work properly, but it isn’t settable when creating a new exhibit or set when importing. Currently there’s no indicator when doing a FTS that a set name hasn’t been set.

The UX around setting an exhibit's Set Name could be more obvious, or users could be warned when they're doing a FTS with no Set Name set. 

## Acceptance Criteria 

- [x] When an Exhibit's FTS set name is set, the FTS checkbox appears under the search bar 
- [x] When an Exhibit's FTS set name is not set, the FTS checkbox does not appear under the search bar

**Comment by bkiahstroud** [comment]
@VanessaVenti off the top of my head, I have a couple suggestions for how we could solve this: 

1. Add Set Name input to New Exhibit form
2. Render warning banner when doing a FTS with no Set Name set

Do you have a preference between these two, or a third option?

**Comment by VanessaVenti** [comment]
@bkiahstroud thanks for thinking about this! Is it just that the FTS set name needs to be filled in before harvesting items? If so, I think it's fine the way it is now. As long as we have it documented where and when to put in the FTS set info that should be fine bc as you mentioned it will mostly just be me and maybe one other person setting up exhibits. As of right now there are only a handful of exhibits that will have corresponding FTS sets, but I'm sure we'll be creating new ones going forward.

In case it helps, here are my thoughts on your ideas:

1. We might not have the FTS set name ready to go at the time of creating a new exhibit, so probably best not to put it there.
2. I like this idea, but I'm not sure how it would work. Where/when were you thinking the warning banner might appear? How would they system know if it has a corresponding FTS set?

**Comment by bkiahstroud** [comment]
@VanessaVenti -- 

>Is it just that the FTS set name needs to be filled in before harvesting items?

Records can be harvested without issue if no FTS set name is set. The FTS set name just needs to be set before anyone starts trying to do full text searches. 

---

>Where/when were you thinking the warning banner might appear? 

I was thinking of putting it at the top of the search results only under two conditions: 

1. If the search  was a FTS 
2. If the exhibit does not have a set name configured 

Otherwise, it won't appear. Here's a very crude mock up: 

![hospital - CURIOSity Demo Site - Harvard Curiosity Search Results 2022-08-30 at 11 24 49 AM](https://user-images.githubusercontent.com/32469930/187515027-0034935d-9f8e-47dd-bc84-3eee6dda5ff0.jpg)

---

>How would they system know if it has a corresponding FTS set?

This would actually be pretty simple; on the page, we have access to the "current" exhibit's database record, so we would simply put the banner behind a conditional like this: `if @current_exhibit.set_name.present?`

**Comment by VanessaVenti** [comment]
Ah, thanks for explaining that @bkiahstroud. I believe the plan is to only show the 'Search inside text of items' check box when an FTS set name has been filled in the admin UI. That should eliminate the need for any warnings to end-users. @summer-cook and @enriquediaz is that your understanding as well?

**Comment by bkiahstroud** [comment]
Related MR: https://gitlab.com/notch8/harvard-curiosity/-/merge_requests/152

**Comment by VanessaVenti** [comment]
Looks good on QA
