### ISSUE TITLE
Add /healthcheck endpoint using rails-healthcheck gem

### ISSUE THREAD

**Issue by dl-maura** [harvard-lts/CURIOSity#169]
Ops needs a health check endpoint to hit, and we have done this in HGL, so we will eb doing this here. Provides a lightweight /healthcheck route for the Ops health check

**Comment by phil-plencner-hl** [comment]
rails-healthcheck gem has been installed: https://github.com/linqueta/rails-healthcheck

This creates a route here:
https://localhost:21407/healthcheck

Merge Request in Gitlab is here: 
https://gitlab.com/notch8/harvard-curiosity/-/merge_requests/147

**Comment by phil-plencner-hl** [comment]
Merged to `main` in Github. PR here:
https://github.com/harvard-lts/CURIOSity/pull/168
