### ISSUE TITLE
Exhibit Specific Fields are not working

### ISSUE THREAD

**Issue by VanessaVenti** [harvard-lts/CURIOSity#170]
I tried creating some Exhibit Specific Fields on a couple exhibits and could not get any to work as expected. None appeared in the search results or item detail pages even though they were mapped in the YAML. In one case I could not even get the field to display in the DISPLAY AND ORDER METADATA FIELDS section of the Configuration > Metadata page.

Some questions about creating them:
1. When setting them up, when do I check the 'Multi-valued?' checkbox? (this is new to Spotlight 3.0)
2. How do we create ones that overlap with the new default list of fields? For example, our [IOHP exhibit](https://curiosity.lib.harvard.edu/iranian-oral-history-project) will use the [iohp.yml](https://github.com/harvard-lts/spotlight-oaipmh-resources/blob/job_entry/harvard_yaml_mapping_files/mods/iohp.yml) that has both Language and Subjects as does the [curiosity.yml](https://github.com/harvard-lts/spotlight-oaipmh-resources/blob/job_entry/harvard_yaml_mapping_files/mods/curiosity.yml) but each of the YAMLs pull in different mods paths.

**Comment by VanessaVenti** [comment]
@bkiahstroud - not sure if this is already on your radar or not. I just tested and found this issue and wanted to make sure you were aware of it while working on harvesting stuff.

**Comment by bkiahstroud** [comment]
@VanessaVenti I haven't yet, but I haven't done much with custom fields so far. Could you provide me with the steps you took to get the issues you're seeing?

**Comment by VanessaVenti** [comment]
@bkiahstroud sure thing, here's what I did:

1. Created a new exhibit (not from import)
2. Added the following exhibit specific metadata fields: ![Screen Shot 2022-09-02 at 10 26 52 AM](https://user-images.githubusercontent.com/60190174/188171163-247e0610-
45cd-4e1d-8282-79d215af9e79.png)
I set all to controlled vocabulary except for Bibliographic Note which I set to Free text as that's what I saw for each in the iohp.yml. I wasn't sure when to check the multi-valued check box so I checked it for Inteviewee and Gender, but not Language. (I later realized Language is already a default field, hence my second question above.) 
3. Harvested the iohp set to the exhibit using the iohp.yml
4. Resulted in these facets displaying in the admin panel: ![Screen Shot 2022-09-02 at 10 36 22 AM](https://user-images.githubusercontent.com/60190174/188173957-ba112bef-e943-453b-b607-79e827588305.png) and these displaying to end users: 
![Screen Shot 2022-09-02 at 10 36 43 AM](https://user-images.githubusercontent.com/60190174/188174063-ccc938ab-8c82-4cd3-bd53-e233422f3123.png) and only the title appeared for metadata in all views.

**Comment by VanessaVenti** [comment]
@bkiahstroud - I also tried adding an exhibit specific field to the demo exhibit that Maura had imported from Prod. This time I had already harvested the demo items before I added the exhibit specific field (not sure if that makes a difference, it doesn't currently in 2.0). In this case, here's what I did:
1. Added 'Permalink ward' as an exhibit specific free text field as I know there are ward items in this set so that permalink should show up for those items.
2. This was the case I mentioned above where 'Permalink ward' did NOT show up in the DISPLAY AND ORDER METADATA FIELDS section of the Configuration > Metadata page.
3. I then harvested the demo set again using the curiosity.yml (which has the permalink-ward field mapped in it)
4. It resulted in not displaying that field for items I know that is should have (for example, [this item on the live site](https://curiosity.lib.harvard.edu/demo/catalog/47-W388045_URN-3:HPREWARD:1182583) is in both demo and ward and therefore should have that permalink if you want to run your own test)
5. I also noticed this time it showed 97 item harvested even though there are still only 96 items in the set so I'm not sure what that is all about. I only see 96 items in the end-user UI, so I think there are only harvested. This looks like it might be an unrelated harvesting bug as I'm pretty sure I've seen this before when harvesting the demo set more than once.
![Screen Shot 2022-09-02 at 10 59 55 AM](https://user-images.githubusercontent.com/60190174/188178237-86f048dc-316b-4d6c-9683-6937420de191.png)

**Comment by bkiahstroud** [comment]
Related PR: https://github.com/harvard-lts/spotlight-oaipmh-resources/pull/35

**Comment by VanessaVenti** [comment]
@bkiahstroud - I'm testing this now, but I'm wondering if you had any insight on the questions in the description:

1. When setting up exhibit specific fields, when do I check the 'Multi-valued?' checkbox? (this is new to Spotlight 3.0)
2. How do we create ones that overlap with the new default list of fields? For example, our [IOHP exhibit](https://curiosity.lib.harvard.edu/iranian-oral-history-project) will use the [iohp.yml](https://github.com/harvard-lts/spotlight-oaipmh-resources/blob/job_entry/harvard_yaml_mapping_files/mods/iohp.yml) that has both Language and Subjects as does the [curiosity.yml](https://github.com/harvard-lts/spotlight-oaipmh-resources/blob/job_entry/harvard_yaml_mapping_files/mods/curiosity.yml) but each of the YAMLs pull in different mods paths.

I'm going to try exporting and importing as I normally would for IOHP which has a bunch of exhibit specific fields and see what happens. My hope is it will only create the fields that don't overlap and reuse the ones that do such as Language. But it would be helpful to know when we are supposed to check 'Multi-valued?'. I would guess whenever it is a Controlled Vocabulary field, but if so I'm not sure what the point of the check box is.

**Comment by phil-plencner-hl** [comment]
@VanessaVenti I dug into the Spotlight Github repository and found the Pull Request that describes what "Multi-Valued' is supposed to do:

https://github.com/projectblacklight/spotlight/pull/2197

Hopefully this is helpful context?

I found this in the issue queue where in 2017 Randy Stern commented that it was "very important for Harvard". Not sure if that is still the case!

https://github.com/projectblacklight/spotlight/issues/1783

cc: @bkiahstroud

**Comment by bkiahstroud** [comment]
@VanessaVenti -- 

>1. When setting up exhibit specific fields, when do I check the 'Multi-valued?' checkbox? (this is new to Spotlight 3.0)

The only difference I saw it make when working on this ticket was that it adds a button next to multi-valued fields in the UI that let you add more than one value: 

![Curation - Add items demo - Notch8 Staging 2022-09-16 at 12 10 59 PM](https://user-images.githubusercontent.com/32469930/190713688-e9dcf6b9-3a87-4e96-94e0-9ee9bc3728e0.jpg)

In my limited metadata experience, almost all fields are multi-valued unless there's a specific reason for them to be singular (e.g. an identifier like URN). 

---

>2. How do we create ones that overlap with the new default list of fields?

You shouldn't need to create any fields that overlap with the default fields. The paths in the mapping files can be different and still use the same Language field, for example. In fact, I think you should try to avoid creating exhibit-specific fields that overlap with the defaults. Earlier in the project we saw conflicting fields causing problems (e.g. neither would render on an individual item page).

**Comment by VanessaVenti** [comment]
Thanks @bkiahstroud and @phil-plencner-hl! Yes, that makes sense that pretty much everything should be multi-value unless it is like a URN or record ID. I realize now I was conflating multi-valued and facetable and now see the difference :).

My test with IOHP looks really good except for one weird thing with Language. I see it display properly as a facet and it shows on the item detail page, but it doesn't display in the list view even though I have the box checked:
<img width="620" alt="Screen Shot 2022-09-16 at 3 52 45 PM" src="https://user-images.githubusercontent.com/60190174/190725261-a4636614-bcf1-4e01-97d0-647c22aed42f.png">
Everything else looks good metadata-wise.

**Comment by VanessaVenti** [comment]
I also tested adding a permalink and that looks good now so I'm going to close this ticket and create a new one with the Language bug I saw. I'm hoping that will get cleared when https://github.com/harvard-lts/CURIOSity/issues/136 is done - we'll see!
