### ISSUE TITLE
Remove old infrastructure repos from internal GitHub

### ISSUE THREAD

**Issue by enriquediaz** [harvard-lts/CURIOSity#174]
Once CURIOSity 3.0 is in full production, we'll clean house and archive or delete outdated repositories. These include older infrastructure projects hosted on HUIT's internal GitHub instance:

- [curiosity](https://github.huit.harvard.edu/LTS/curiosity)
- [DSI_CURIOSity_cfg](https://github.huit.harvard.edu/LTS/DSI_CURIOSity_cfg)

We also need to change the default branch of CURIOSITY-IF to `main` and delete the `master` branch
- [CURIOSity-IF](https://github.huit.harvard.edu/LTS/CURIOSity-IF)

**Comment by phil-plencner-hl** [comment]
`main` branch has been set as default branch of CURIOSITY-IF and the `master` branch has been deleted.

**Comment by dl-maura** [comment]
@phil-plencner-hl and I don't have the power to archive the other 2 things @enriquediaz do you?

**Comment by dl-maura** [comment]
Done per @enriquediaz
