### ISSUE TITLE
Remove extra black translucent box style that comes up with FTS bar

### ISSUE THREAD

**Issue by summer-cook** [harvard-lts/CURIOSity#175]
![Image](https://user-images.githubusercontent.com/73361970/188657376-fa03afb5-c6a1-4779-b37b-5698cd73f65a.png)

**Comment by bkiahstroud** [comment]
Also viewable on our staging ([example link](https://staging-harvard-curiosity.notch8.cloud/contagion))

**Comment by jeremyf** [comment]
Code for review at: https://gitlab.com/notch8/harvard-curiosity/-/merge_requests/157

**Comment by phil-plencner-hl** [comment]
This has been fixed and deployed to QA: 
https://curiosity-qa.lib.harvard.edu/contagion/catalog?exhibit_id=contagion&search_field=all_fields&q=hospital&fulltext=yes
