### ISSUE TITLE
Create an FTS Search from a default (metadata) search

### ISSUE THREAD

**Issue by dl-maura** [harvard-lts/CURIOSity#197]
Right now, when I perform an FTS Search, I am given the option/notification that I'm searching FTS and would I like to do a metadata search instead. We would like this to happen in the reverse as well. When I do a metadata search, have a notification asking me if I'd prefer to do a FTS Search. 

[Default metadata search mockup](https://www.sketch.com/s/39eb3859-75e8-4add-8498-6cbf2934d73c/a/bgJyvqo) (screenshot below)
- [x] Add the following message when someone does NOT check the 'Search inside text of items' checkbox: 'You searched ALL METADATA FIEDS for: [search term] / Searchable text from transcripts or OCR is available for some items. [Search inside text of items instead](url).

![Screen Shot 2022-09-15 at 4 35 55 PM](https://user-images.githubusercontent.com/60190174/190503880-e8bff0fa-2d5e-4b17-b958-ec81aa275c46.png)

**Comment by jeremyf** [comment]
@bkiahstroud Here's where I believe the conditional is for that rendering: `./app/views/catalog/_search_form.html.erb`

https://gitlab.com/notch8/harvard-curiosity/blob/3c80d6e355d9882b5d330f7f6e691622981b9dd9/app/views/catalog/_search_form.html.erb#L27-32

**Comment by bkiahstroud** [comment]
GitHub PR: https://github.com/harvard-lts/CURIOSity/pull/204

**Comment by VanessaVenti** [comment]
Looks good on QA!
