### ISSUE TITLE
Page parameter missing for raw objects

### ISSUE THREAD

**Issue by VanessaVenti** [harvard-lts/CURIOSity#205]
## Summary

Some of our URNs for page turned objects should resolve to a page within the object. For example:

[ARN00007C00040 in LibraryCloud](https://api.lib.harvard.edu/v2/items?recordIdentifier=ARN00007C00040) has a raw object URN of https://nrs.harvard.edu/urn-3:FMUS.ARN:37536131 that resolves to https://iiif.lib.harvard.edu/manifests/view/drs:457731773$39i (note that $39 indicates page number 39)

However when this item is harvested into Spotlight 3.0, the iframe link is https://nrs.harvard.edu/urn-3:FMUS.ARN:37536131:VIEW which resolves to https://iiif.lib.harvard.edu/manifests/view/drs:457731773$1i (the first page of the object)

This item is in the demo collection set where you can see it [resolves properly in 2.0](https://curiosity.lib.harvard.edu/demo/catalog/47-arn00007c00040). The correct thumbnail does display in 3.0, it is just the raw object on the item detail page that does not go to the right page.

## Testing Instructions

1. Login as an admin 
2. Harvest the demo set 
3. Compare each item in the Acceptance Criteria with its mirror on [the old site](https://curiosity.lib.harvard.edu/demo) to ensure the image displayed in the Mirador viewer match 

_Demo: https://drive.google.com/file/d/1YuYHqK0MCnhSIzbBLWLBC5NSFxon6Xn3/view?usp=sharing_

## Acceptance Criteria

The Mirador viewer on the individual item pages with the following IDs render with the correct page number: 

**NOTE:** the `1-` prefix is the ID of the exhibit; your demo exhibit's ID may be different 

- [x] `1-ARN00007C00040`
- [x] `1-FAR00033C00025`
- [x] `1-GRA00002C00044`
- [x] `1-ECB00010C00030`
- [x] `1-ORC00002C00093`

### Developer notes

- [ ] Add `n` param to Mirador `iframe` URL when parsing metadata during harvest 
- [ ] When doing a FTS, strip `n` param out in favor of `pageOrder` param

**Comment by bkiahstroud** [comment]
Related MR: https://gitlab.com/notch8/harvard-curiosity/-/merge_requests/174 
Sister PR: https://github.com/harvard-lts/spotlight-oaipmh-resources/pull/37

**Comment by bkiahstroud** [comment]
GitHub PR: https://github.com/harvard-lts/CURIOSity/pull/206

**Comment by VanessaVenti** [comment]
Looks good on QA!
