### ISSUE TITLE
Only display the FTS hint alert if the exhibit has a FTS Set Name

### ISSUE THREAD

**Issue by phil-plencner-hl** [harvard-lts/CURIOSity#207]
When searching in an exhibit that doesn't have an FTS Set Name, like Early Photography of Japan, a hint alert box displays at the top of the search results that looks like this:

> Searchable text from transcripts or OCR is available for some items. Search inside text of items instead.

Clicking on the "Search inside" link throws a rails error. 

Example: 
https://curiosity-qa.lib.harvard.edu/vv-import-test-2022-09-07/catalog?search_field=all_fields&q=plate

The alert box should only be displayed on the search results of exhibits that have a FTS Set Name. This is likely similar to the logic used for displaying the "Search inside text of items" checkbox in the exhibit's search form.

**Comment by bkiahstroud** [comment]
Related MR: https://gitlab.com/notch8/harvard-curiosity/-/merge_requests/176
