### ISSUE TITLE
Translated title/multivalued titles on new lines (see MPCOL)

### ISSUE THREAD

**Issue by VanessaVenti** [harvard-lts/CURIOSity#211]
### Acceptance Criteria
- [x] Translated title appears on a new line under title

Translated title is not appearing on MPCOL records. For example, https://api.lib.harvard.edu/v2/items?q=LN10 has a translated title of "The Song of Bagdad" which displays in 2.0: https://curiosity.lib.harvard.edu/milman-parry-collection-of-oral-literature/catalog/30-LN10, but does not display in 3.0.

Here is the info to use when testing this exhibit:
- [Exhibit json (has lots of exhibit specific fields)](https://drive.google.com/file/d/1JG5utuK6BjqV3gc35lwINunDtkOx6hAl/view?usp=sharing)
- Base URL: https://api.lib.harvard.edu/oai/
- Set Name: mpcol
- Mapping File: [mpcol.yml](https://github.com/harvard-lts/spotlight-oaipmh-resources/blob/main/harvard_yaml_mapping_files/mods/mpcol.yml)

**Comment by bkiahstroud** [comment]
Related MR: https://gitlab.com/notch8/harvard-curiosity/-/merge_requests/181 

**NOTE:** nothing needs to be reharvested. This was an issue with how the UI was displaying the data.

**Comment by VanessaVenti** [comment]
Translated title is now appearing, but it needs to be moved it its own line instead of being separated by ' and ' after the title.

**Comment by bkiahstroud** [comment]
Related MR: https://gitlab.com/notch8/harvard-curiosity/-/merge_requests/186

**Comment by VanessaVenti** [comment]
Looks good on QA!
