### ISSUE TITLE
Improve error reporting in harvesting modal

### ISSUE THREAD

**Issue by bkiahstroud** [harvard-lts/CURIOSity#215]
## Summary

Sometimes, a harvest will seemingly spin endlessly without saying anything is wrong in the "Recent indexing activity" harvest status modal. Eventually, it may even report that the job succeeded. However, when looking in the DelayedJob dashboard (`/delayed_job/overview`), the harvest job is clearly throwing an error. 

We need to extend the harvest tracking to include these currently uncaptured errors so we can make them visible to users in the Exhibit Dashboard. 

## Testing Instructions

1. Login as an admin
2. Harvest the **demo** set
3. Navigate to the Exhibit Dashboard 
4. Verify the Acceptance Criteria 

## Acceptance Criteria 

- [x] `X of Y (Z errors)` message should not appear more than once in the modal (indicates job re-ran multiple times) 
- [x] Warnings should appear as yellow rows in the modal

**Comment by bkiahstroud** [comment]
Related PR: https://github.com/harvard-lts/spotlight-oaipmh-resources/pull/40

**Comment by bkiahstroud** [comment]
@VanessaVenti or @dl-maura -- when you're able, can you replace the `<set>` in the Testing Instructions with the set that was causing the issue described by this ticket?

**Comment by VanessaVenti** [comment]
@bkiahstroud - it was demo, I've updated the description above and Phil is testing right now
