### ISSUE TITLE
Add Set spec to indexing table

### ISSUE THREAD

**Issue by VanessaVenti** [harvard-lts/CURIOSity#217]
- [ ] Add 'Set spec' column before the 'Items indexed' column in the RECENT ITEM INDEXING ACTIVITY table in on the exhibit dashboard page

### Use case
This is helpful for both troubleshooting errors (like if we type the wrong set spec by accident), but also to know the history of sets that are harvested to an exhibit.

### Other ideas
We also discussed adding oai-path, set spec, and yaml used in harvesting (with set spec being the most important) to harvester modal, but we decided the above solution would be more desirable and hopefully an easer lift. If we do want to revisit adding additional info to the modal window here are Kiah's thoughts:

> Adding setSpec to the modal is really easy, but depending how much info we want to add will affect the lift (but probably a light lift?). Would need to bring the view file from spotlight and override it which could make future updates more difficult.

**Comment by dl-maura** [comment]
Dashboard might be an easier list than modal, because we already edited that display

**Comment by VanessaVenti** [comment]
Status from slack:

@mferrarini: I worked on adding a column for “Set Spec” to the reindexing table. It’s just a placeholder column, like it’s not pulling in the actual set spec submitted. @dl-maura  or @phil-plencner-hl, if you know how to pull in the real stuff feel free to jump in and commit it to the branch! Otherwise thinking this second half could be punted over to Kiah?

Branch name: reindexing-table

**Comment by dl-maura** [comment]
https://gitlab.com/notch8/harvard-curiosity/-/tree/reindexing-table

**Comment by phil-plencner-hl** [comment]
I'm not sure if we can get the set spec to show up here without making updates to Spotlight Core. 
This is where the controller is for the dashboard:
https://github.com/projectblacklight/spotlight/blob/main/app/controllers/spotlight/dashboards_controller.rb

The tracker table does not include the set spec, which is where it gets the data to display in the view that @dl-maura  changed:
`spotlight=# \d spotlight_job_trackers;
                                           Table "public.spotlight_job_trackers"
      Column      |            Type             | Collation | Nullable |                      Default 
                      
------------------+-----------------------------+-----------+----------+------------------------------
----------------------
 id               | bigint                      |           | not null | nextval('spotlight_job_tracke
rs_id_seq'::regclass)
 on_type          | character varying           |           | not null | 
 on_id            | bigint                      |           | not null | 
 resource_type    | character varying           |           | not null | 
 resource_id      | bigint                      |           | not null | 
 job_id           | character varying           |           |          | 
 job_class        | character varying           |           |          | 
 parent_job_id    | character varying           |           |          | 
 parent_job_class | character varying           |           |          | 
 status           | character varying           |           |          | 
 user_id          | bigint                      |           |          | 
 log              | text                        |           |          | 
 data             | text                        |           |          | 
 created_at       | timestamp without time zone |           | not null | 
 updated_at       | timestamp without time zone |           | not null | `

**Comment by dl-maura** [comment]
Set spec lives in the harvesters table, that's where we'd want to look per Kiah

**Comment by dl-maura** [comment]
Could be interested in putting this in core!

**Comment by dl-maura** [comment]
Kiah informed me we can get the connection with j.resource (where j is a job tracker instance) and this will show us the set spec (so j.resource.set)

**Comment by phil-plencner-hl** [comment]
Maura C. got it working here is the PR:
https://github.com/scientist-softserv/harvard-curiosity/pull/7

**Comment by VanessaVenti** [comment]
Looks good on QA! Yay, very excited about this one :).
