### ISSUE TITLE
Create FTS sets

### ISSUE THREAD

**Issue by VanessaVenti** [harvard-lts/CURIOSity#226]
- [x] curiosity_contagion
- [x] curiosity_exp
- [x] curiosity_immigration
- [x] curiosity_reading
- [x] curiosity_ww

A set for BTA will also be created once BTA has finalized their item list.

**Comment by dl-maura** [comment]
Sets are zipped and sent to AM for upload

**Comment by dl-maura** [comment]
We seem to be having issues with the FTS set loader
