### ISSUE TITLE
Some default facets are missing config options in UI

### ISSUE THREAD

**Issue by bkiahstroud** [harvard-lts/CURIOSity#233]
## Summary

"Default facets" refers to the facets configured in the `CatalogController` using `config.add_facet_field`. These facets will appear on all exhibits.

Some of the default facets are not rendering in the admin dashboard settings page. 

## User Story

_Using **Series** as an example facet missing its config in this user story_

As an admin user, if I perform a search, I can see the Series facet on the left hand side of the page. If I navigate to the Facet settings in the exhibit dashboard, I don't see any options to configure the Series facet. This means I can't adjust its order in the list of facets are disable its display in the search results.

## Acceptance Criteria

- [x] All default facets display configuration options in the admin dashboard (when populated with data) 

## Testing Instructions 

1. Login as an admin 
2. ...  

## Developer Notes 

The facets configured in the `CatalogController` do not correspond with the settings in the admin dashboard; the settings are represented by a different object in Spotlight. Specifically, it can be found as a hash here: 

```ruby
Spotlight::Exhibit.find_by(slug: <slug>).blacklight_configuration.facet_fields
=> 
{"school-short-name_ssim"=>{"show"=>false, "label"=>"School Short Name", "sort"=>"count"},
 "school-name_ssim"=>{"show"=>true, "label"=>"School Name", "sort"=>"count"},
...
```

I think if we ensure an exhibit's `blacklight_configuration.facet_fields` gets loaded with all the default facet's configurations upon creation of the exhibit, they'll always show up for admins in the UI.

**Comment by VanessaVenti** [comment]
Upon further investigation, it appears this may only be a problem for exhibits using an imported json. Things to test to confirm this:

- [x] 1-Harvest demo to a new exhibit (with no json import) and confirm all facets are controllable
- [ ] 2-Harvest a small set of items to a new exhibit (with no json import) that does not have metadata for all facets. Then harvest demo (which has metadata for all facets) to the same exhibit and confirm all facets are controllable.
- [ ] 3-Import a 2.0 json (with the facet_fields deleted) to a new exhibit and harvest a subset of items and confirm all facets are controllable
- [ ] 4-Harvest the demo set to the exhibit in test 3 above and confirm all facets are controllable

**Comment by dl-maura** [comment]
@phil-plencner-hl and I will look at partial deletes
