### ISSUE TITLE
Create a cascade delete for harvester table

### ISSUE THREAD

**Issue by dl-maura** [harvard-lts/CURIOSity#235]
We discovered that when you delete an exhibit, the harvester lines associated with the purged exhibit aren't deleted, which is causing validation errors.

- [ ] Update the schema to have the cascade delete. When an exhibit is deleted, purge the related lines using exhibit_id from spotlight_harvester table (are there any other tables we think this might be an issue with?)
- [ ] Manually clean up dev/qa/local data

**Comment by bkiahstroud** [comment]
Related MR: https://gitlab.com/notch8/harvard-curiosity/-/merge_requests/193
