### ISSUE TITLE
Import & harvest 'special' exhibits in QA

### ISSUE THREAD

**Issue by VanessaVenti** [harvard-lts/CURIOSity#237]
Most 2.0 exhibits have successfully been imported and harvested into 3.0 QA. The following still need to be imported and harvested:

### 1 - Prod published exhibits to move/harvest to QA
- [ ] South Sea Bubble - able to export via UI
- [ ] Andrew Garrett - able to export via UI, no set to harvest
- [ ] Artemas Ward - error when exporting, but Phil got from the back end
- [ ] Chinese Rubbings - error when exporting, but Phil got from the back end
- [ ] Daguerreotypes - error when exporting, but Phil got from the back end
- [ ] A-cats Faculty - too large to export via UI, used 2.0 QA export, but likely want to recreate manually for beta move
- [ ] A-cats Courses - too large to export via UI, will recreate manually for beta move

### 2 - Prod unpublished exhibits to move/harvest to QA
- [ ] Berenson Art Collection - able to export via UI
- [ ] Hedda Morrison - able to export via UI
- [ ] Susan B. Anthony - able to export via UI (was originally on 2.0 QA so images won't work until updated copy of images is done)
- [ ] Catching the Wave - able to export via UI (was originally on 2.0 QA so images won't work until updated copy of images is done)

### 3 - 3.0 QA exhibits to move/harvest to 3.0 QA
- [x] Black Teacher Archive - recreated, also have file locally
- [ ] Accessibility Testing Exhibit - have file locally, but may want to just use demo instead?

**Comment by VanessaVenti** [comment]
@dl-maura will request redoing the image directory with ops to do the database dump. She will rerun it on QA which will clear any images fixed in QA.

**Comment by dl-maura** [comment]
> too large to export via UI, used 2.0 QA export, but likely want to recreate manually for beta move

We will be remaking this manually, the export isn't correct

**Comment by VanessaVenti** [comment]
Closing this ticket because these were all successfully re-created and harvested in beta (aside from Courses which we are tracking separately). QA was wiped and recreated, so all collections will need to be reharvested if we decide it is worth having a snapshot of them on QA, not just the collections listed in this story. As of right now, we've decided this is not a priority.
