### ISSUE TITLE
Export problem exhibits from 2.0

### ISSUE THREAD

**Issue by VanessaVenti** [harvard-lts/CURIOSity#238]
We are able to export most exhibits from the admin UI in 2.0, but a few are throwing errors or too large and need further troubleshooting:

- [x] [Artemas Ward](https://curiosity.lib.harvard.edu/artemas-ward-house-and-its-collections) - throws error
- [x] [Chinese Rubbings](https://curiosity.lib.harvard.edu/chinese-rubbings-collection) - throws error
- [x] [Daguerreotypes](https://curiosity.lib.harvard.edu/daguerreotypes-at-harvard) - throws error
- [x] [A-Cats Faculty](https://curiosity.lib.harvard.edu/archived-harvard-university-online-course-catalogs-faculty) - too large
- [ ] ~~[A-Cats Courses](https://curiosity.lib.harvard.edu/archived-harvard-university-online-course-catalogs-courses) - too large~~

**Comment by phil-plencner-hl** [comment]
For Artemas Ward, Chinese Rubbings and Daguerreotypes the solution I was able to apply to the old Dev site was this:

https://stackoverflow.com/questions/11470011/activerecordsubclassnotfound

I added the following line to the Resources class:
`self.[inheritance_column](https://apidock.com/rails/ActiveRecord/Base/inheritance_column/class) = :_type_disabled`

Which is located in the blacklight-spotlight Gem here:
https://github.com/projectblacklight/spotlight/blob/b06511be2b93a1dd999aada2405ab8609592804f/app/models/spotlight/resource.rb#L6

After making the change I restarted the Rails app:

`touch /home/dcpadm/prod/tmp.restart.txt`

Voila!

**Comment by phil-plencner-hl** [comment]
LTS Snow ticket opened:  INC04712751.

**Comment by dl-maura** [comment]
Courses will need to be rebuilt
