### ISSUE TITLE
Hyperlink links in list view

### ISSUE THREAD

**Issue by VanessaVenti** [harvard-lts/CURIOSity#254]
- [x] In search results on List view on 'No Thumbnail Or Viewer' theme, hyperlink audio and transcript links. [See IOHP on QA as an example for each of these](https://curiosity-qa.lib.harvard.edu/iohp/catalog?search_field=all_fields)

**Comment by mferrarini** [comment]
this is working again on QA, though the links needed to be restyled. Changes were made in the https://github.com/scientist-softserv/harvard-curiosity/pull/5 pull request.

QA:
![Screenshot 2022-11-17 at 16-53-24 - Iranian Oral History Project - Spotlight 3 0 QA Search Results](https://user-images.githubusercontent.com/13121501/202568057-b60351d0-c1dc-4e0f-9415-9144ee963326.png)

New style:
![Screenshot 2022-11-17 at 16-54-15 - Iranian Oral History Project - CURIOSity Digital Collections Search Results](https://user-images.githubusercontent.com/13121501/202568079-0d5a3401-3ba7-40ce-a39f-b66523caecaf.png)

**Comment by VanessaVenti** [comment]
Looks great on QA!
