### ISSUE TITLE
Accessibility audit of Spotlight 3.0

### ISSUE THREAD

**Issue by VanessaVenti** [harvard-lts/CURIOSity#27]
### [CURIOSity 3.0 Accessibility Audit](https://docs.google.com/document/d/1ORtzO7R3pQpGHXUeqHLC6dBX_oL3GqjEI0wYPUyIZrw/edit?usp=sharing)

**Comment by VanessaVenti** [comment]
Meg will test once we cut over to 3.0 where the demo links will be stable.

**Comment by VanessaVenti** [comment]
The accessibility review is complete and the report is linked in the description. Moving to 'Ready for development'.

**Comment by enriquediaz** [comment]
This work has been prioritized as a "Must Do" for [LTS Maintenance Sprint 8](https://docs.google.com/spreadsheets/d/1IOBdddJg6GYK6i78QL31ery5Q0PyyxVZ-BTossZGMQA/edit#gid=1989190906). I've created a Jira ticket. [LTSMAINT-652](https://jira.huit.harvard.edu/browse/LTSMAINT-652), to track the progress once the work is underway .
