### ISSUE TITLE
Update Homepage and Header

### ISSUE THREAD

**Issue by phil-plencner-hl** [harvard-lts/CURIOSity#270]
The CURIOSIty Collections title in the header needs to have the proper capitalization.

The HTML title needs to be: CURIOSity Digital Collections

The homepage title needs to be:
CURIOSity Digital Collections
Curated views that provide specialized search options and unique content

**Comment by phil-plencner-hl** [comment]
PR: https://github.com/scientist-softserv/harvard-curiosity/pull/26

**Comment by phil-plencner-hl** [comment]
Deployed to Dev and QA.

**Comment by VanessaVenti** [comment]
Looks good on QA!
