### ISSUE TITLE
Cannot Search Within Browse categories

### ISSUE THREAD

**Issue by dl-maura** [harvard-lts/CURIOSity#295]
VV found that when someone tries to search within a browse category, they get an error message. This is because the clear all button can't generate on this page -- I think because the code is trying to pass a value into that method to only clear some, but that doesn't work.

There's a few options I can see:
- don't generate the clear all on the browse searches
- figure out a way to make clear all work with the browse categories so that It can be generated on this page
  - making a new method that takes an option parameter to do the clear some
  - making the clear all send you back to the main search page?

https://curiosity.lib.harvard.edu/demo/browse/ceramics
https://curiosity.lib.harvard.edu/american-currency/browse/browse-all-items

Affected sites:
https://curiosity.lib.harvard.edu/american-currency/browse
https://curiosity.lib.harvard.edu/chinese-rare-books/browse
https://curiosity.lib.harvard.edu/demo/browse/ceramics

**Comment by dl-maura** [comment]
The clear all button is a Harvard-developed thing, we think it came from HDC?

**Comment by enriquediaz** [comment]
"Clear all" is actually the "Start over" button you see in distro Blacklight ([example](https://demo.projectblacklight.org/?search_field=all_fields&q=maine)); all we did was change the label of the button

**Comment by dl-maura** [comment]
Current solution: we removed the button from displaying in the browse pages. This might not be the 'ideal' but will allow those pages to function. In QA for @VanessaVenti

**Comment by VanessaVenti** [comment]
This works good enough for now! I've recorded the styling and behavior issues we'll want to investigate later here: https://github.com/harvard-lts/CURIOSity/issues/296
