### ISSUE TITLE
Pages widget is buggy

### ISSUE THREAD

**Issue by VanessaVenti** [harvard-lts/CURIOSity#302]
- You can't add more than 3 pages
- SSB reported being unable to find Timeline or the Iconography pages using Chrome. Intermittent issue with Edge and FF. 
  - VV was able to get both to load using Chrome in both QA & Prod

Need test if these are issues in vanilla.

**Comment by dl-maura** [comment]
We determined that the second issue is in fact a permissions problem

**Comment by VanessaVenti** [comment]
I documented the 3 page limitation on the service site and the second issue is being tracked on https://github.com/harvard-lts/CURIOSity/issues/303 so I'll close this one.
