### ISSUE TITLE
Update curiosity.yml

### ISSUE THREAD

**Issue by VanessaVenti** [harvard-lts/CURIOSity#306]
Replace [curiosity.yml on Github](https://github.com/harvard-lts/spotlight-oaipmh-resources/blob/main/harvard_yaml_mapping_files/mods/curiosity.yml) with: https://drive.google.com/file/d/1FJgDcedDBtulBPvIUH27Xw3EblWpSs8o/view?usp=share_link

Changes:
2023-02-21: Added permalink xpath for woc (VV)

**Comment by dl-maura** [comment]
@VanessaVenti I think I did this? can you confirm?

**Comment by VanessaVenti** [comment]
@dl-maura it looks like the old one still. Just a heads up, I am in the process of making more updates for BTA so there will be another version with more updates soon.
