### ISSUE TITLE
Stale Cookie Problems

### ISSUE THREAD

**Issue by dl-maura** [harvard-lts/CURIOSity#308]
We have an issue where cookies become stale, but rather than logging a user out, they just can't do really anything. The work-around is a private window, but these cookies should expire in a way that prompts a re-login and not the current behavior.

## Testing instructions
- [x] In a private window (so you aren't logged in) try to go to: https://curiosity-qa.lib.harvard.edu/site/edit You should be sent to HarvardKey and NOT get a window about how you aren't authorized (which happens now even post login)
- [x] THEN wait like 2 hours and try to go to an admin thing. When you get asked to HKey again (or get auto refreshed) you should NOT see a message about needing to re log in. We basically hid the two expiry messages because they aren't applicable to our system

**Comment by VanessaVenti** [comment]
VV was only able to log in via an incognito window on 2023-03-23, so she cleared her cache for https://curiosity.lib.harvard.edu/ which resolved the problem for non-private windows. Noting this here to see how long it takes for the issue to reoccur.

**Comment by VanessaVenti** [comment]
This looks good to me on QA!

**Comment by dl-maura** [comment]
@VanessaVenti did we fix this? I think we fixed this?

**Comment by VanessaVenti** [comment]
@dl-maura yes, this is fixed - I'll go ahead and close!
