### ISSUE TITLE
Add Google Analytics

### ISSUE THREAD

**Issue by VanessaVenti** [harvard-lts/CURIOSity#34]
Investigate updating Google Analytics for the following reasons:

1. Google Analytics 4 is replacing Universal Analytics. On July 1, 2023, standard Universal Analytics properties will no longer process data. You'll be able to see your Universal Analytics reports for a period of time after July 1, 2023. However, new data will only flow into Google Analytics 4 properties. See https://support.google.com/analytics/answer/10089681?hl=en for details.
2. Align Google Analytics implementation with Harvard Digital Collections’ use of event tracking and tagging. Add external URL tracking?

**Comment by mferrarini** [comment]
New code has been updated to use our new tag manager tracking id.
Domain name curiosity.library.harvard.edu has been added to GA4 for cross-domain tracking.

**Comment by dl-maura** [comment]
You can't test this on dev/qa because we don't actually track metrics, can use Tag Manager (Maura F. knows how to do this) to preview

**Comment by mferrarini** [comment]
Quick video of me testing that google analytics is firing on QA:

https://user-images.githubusercontent.com/13121501/202523478-1a856835-a1c9-4021-8d58-4cdc8e9632e5.mp4

**Comment by VanessaVenti** [comment]
Thanks @mferrarini - I'll go ahead and close this one!
