### ISSUE TITLE
Enable support team to utilize Github

### ISSUE THREAD

**Issue by VanessaVenti** [harvard-lts/CURIOSity#36]
Provide the CURIOSity support team with documentation and instructions on how to utilize GITHUB enterprise for storing versioned materials to produce the exhibits, particularly YML files.

**Comment by dl-maura** [comment]
VV needs access oai-pmh repository for pull requests

**Comment by VanessaVenti** [comment]
@dl-maura showed me how to do this on Tuesday - thanks Maura!
