### ISSUE TITLE
Update harvester ?buttons=y customization

### ISSUE THREAD

**Issue by VanessaVenti** [harvard-lts/CURIOSity#37]
### Update
This customization is no longer needed as the fix for https://github.com/harvard-lts/CURIOSity/issues/91 and https://github.com/harvard-lts/CURIOSity/issues/205 have fixed this issue.

### Acceptance criteria
Harvest demo set and check the viewer loads on the following records:
- [x] 990119758800203941
- [x] 990119758280203941
- [x] 990119761340203941

### History
In Spotlight 2.0, the harvester had a modification to append ?buttons=y to still image raw object URNs in order to enable the Mirador viewer. This customization did not take into account if the URN has already been appended with ?buttons=Y and therefore needs to be updated to replace "?buttons=Y" with "?buttons=y"

Islamic Heritage Project has 69 URNs with ?buttons=Y appended to them that prevent the viewer from loading in prod 2.0: https://curiosity.lib.harvard.edu/islamic-heritage-project/catalog?f%5Bdigital-format_ssim%5D%5B%5D=Images&page=1&search_field=all_fields

**Comment by dl-maura** [comment]
This might be something to ask IIIF team about

**Comment by dl-maura** [comment]
Remove any parameters from the URN that are not parameter N, add ":view", work with AM on this?

Read parameters
Remove extraneous parameters
Then add ":view"

**Comment by VanessaVenti** [comment]
@bkiahstroud I just updated the description on this on to say it was fixed with the same fix for [#205](https://github.com/harvard-lts/CURIOSity/issues/205). In it looks good to me when testing it, but I just wanted to confirm the reason for the fix sounds right to you. If so, I'll go ahead and close this one.

**Comment by bkiahstroud** [comment]
@VanessaVenti I think this might have actually been fixed by https://github.com/harvard-lts/CURIOSity/issues/91, but #205 is definitely related so linking either/both doesn't hurt.

**Comment by VanessaVenti** [comment]
Thanks so much, @bkiahstroud - I've linked both in the description.
