### ISSUE TITLE
Item detail page not displaying on 'No Thumbnail Or Viewer' theme

### ISSUE THREAD

**Issue by VanessaVenti** [harvard-lts/CURIOSity#385]
## Description
The item detail page (aka item record page) is not displaying on the 'No Thumbnail Or Viewer' theme. The following collections use this theme and are effected:
- [Ming](https://curiosity.lib.harvard.edu/index-ming-dynasty-chinese-paintings)
- [Courses](https://curiosity.lib.harvard.edu/archived-harvard-university-online-course-catalogs-courses)
- [Calendars](https://curiosity.lib.harvard.edu/archived-harvard-university-online-course-catalogs-calendars)
- [Faculty](https://curiosity.lib.harvard.edu/archived-harvard-university-online-course-catalogs-faculty)
- [IOHP](https://curiosity.lib.harvard.edu/iranian-oral-history-project) Note: some records in this collection display and some don't, for example:
  - Displays: [ABADIAN__BAHMAN01](https://curiosity.lib.harvard.edu/iranian-oral-history-project/catalog/32-ABADIAN__BAHMAN01)
  - Doesn't display: [ADAMIYATT__TAHMOURESS06](https://curiosity.lib.harvard.edu/iranian-oral-history-project/catalog/32-ADAMIYATT__TAHMOURESS06)

## Workaround
As a temporary workaround, we have turned on the display of all metadata in List view for all the collections above except for IOHP. In IOHP, many item detail pages appear to display and the search results in list view would be very long if all record metadata appeared here. IOHP is a very heavily used collection and no one has reported the issue on this site yet that we know of. If it becomes an issue we can consider displaying all metadata in List view for this collection as well.

## When resolved
Once resolved, List view can go back to displaying only the following fields:
- [x] Ming - Description, Artist, Format, Painting Location
- [x] Calendars - Description, School Name, Semester, Year
- [x] Faculty - School Name, Department, Academic Year
- [x] Courses - School Name, Semester, Start Year
- [x] IOHP - Description, Interviewee, Language, Interviewer, Interview Date, Audio, Transcript (and notify curator the issue has been fixed)

**Comment by phil-plencner-hl** [comment]
PR with the fix is here:
https://github.com/harvard-lts/CURIOSity/pull/386

**Comment by VanessaVenti** [comment]
Looks good on both QA and prod!
