### ISSUE TITLE
PDS objects in are no longer loading the right page

### ISSUE THREAD

**Issue by VanessaVenti** [harvard-lts/CURIOSity#410]
1/17/23 - Botany library reported that the images in Botanical Illustrations are no longer loading the right page of the PDS object and instead always loading the first page.

For example, this search for ARN00007C00003: https://curiosity.lib.harvard.edu/botanical-illustrations/catalog?exhibit_id=botanical-illustrations&q=ARN00007C00003&search_field=all_fields correctly displays the correct thumbnail (which is the image on page 3), but when you go to the item detail page: https://curiosity.lib.harvard.edu/botanical-illustrations/catalog/62-ARN00007C00003 you are taken to the first page of the PDS object instead of page 3. I can confirm that CURIOSity used to take you to the correct page before the recent IDS work.

I tried to reharvest this item to see if that made a difference and it did not. I also checked this item out in both Hollis for Archival Discovery and HDC and can see you are correctly taken to the right page in both places:

HAD - https://hollisarchives.lib.harvard.edu/repositories/15/archival_objects/2209257
HDC - https://digitalcollections.library.harvard.edu/catalog/arn00007c00003

So the issue seems to be specific to CURIOSity. This issue effects most of the 4,147 items in this collection and effects other items in other collections as well.

Enrique - As an initial investigative measure, we're going to examine the Embed Service code that was incorporated into CURIOSity late last year, because that appears to be the key difference between it and HAD and HDC. The theory is that the component in the request string corresponding to the page that should load is either ignored or lost in the string of transactions that deliver the image to the user via Mirador.

**Comment by VanessaVenti** [comment]
https://github.com/harvard-lts/CURIOSity/pull/404

**Comment by phil-plencner-hl** [comment]
This has been deployed and is confirmed to be working:
https://curiosity-qa.lib.harvard.edu/botanical-illustrations/catalog/62-ARN00007C00003
(You may have to clear browser cache if you have recently viewed an item)
