### ISSUE TITLE
Staging - Saving when creating an exhibit, or navigating to an unpublished exhibit causes an error

### ISSUE THREAD

**Issue by crisr15** [harvard-lts/CURIOSity#48]
# Summary

When I try to create a new exhibit or when I go to view a non- published exhibit I get an error.  Exhibits seem to be saving as they show up under unpublished but can still not be accessed.  

Sentry error: 
https://sentry.notch8.com/sentry/harvard-curiosity/issues/140403/
https://sentry.notch8.com/sentry/harvard-curiosity/issues/140402/
# Acceptance Criteria
- [ ] I can create a new exhibit
- [ ] I can visit an already created exhibit as an admin or curator
# Screen shot of where to click to reproduce the error
![Create a new exhibit Blacklight 2022-04-13 at 3 01 54 PM](https://user-images.githubusercontent.com/11359350/163277978-33e4a56f-0631-4489-959c-1200de565adb.jpg)

![Unpublished exhibits Blacklight 2022-04-13 at 3 06 09 PM](https://user-images.githubusercontent.com/11359350/163278274-2c5c7fe7-3afd-4d2e-b6af-118f9e1ec428.jpg)

**Comment by aprilrieger** [comment]
I was able to update the solr password env variable and resolved the solr issue and now we have a permissions issue with the tmp dir: https://sentry.notch8.com/sentry/harvard-curiosity/issues/140404/ 
```
Permission denied @ rb_sysopen - /app/spotlight/tmp/cache/assets/sprockets/v4.0.0/I2/I2……
```
