### ISSUE TITLE
Migrate Solr for data TEDs to QA and PROD

### ISSUE THREAD

**Issue by VanessaVenti** [harvard-lts/CURIOSity#50]
Data TEDs were harvested from the DEV Solr environment; need to move complete PROD data over. 

Anthony will set this up and Vanessa will test harvesting in QA.

Outstanding question - What is the next step for connecting LTS and the Registrar to harvest recent A-cats data? Last harvest was spring 2018.

**Comment by dl-maura** [comment]
Follow up with AM about this

**Comment by dl-maura** [comment]
@VanessaVenti This might be done? I know there is a question about data cleanup is that a separate ticket?

**Comment by dl-maura** [comment]
AS is double checking courses

**Comment by VanessaVenti** [comment]
Data looks good on 2.0 QA! Looking at the data in 3.0 is being tracked on #219.
