### ISSUE TITLE
Pre-publish exhibits

### ISSUE THREAD

**Issue by VanessaVenti** [harvard-lts/CURIOSity#52]
Implement ability to publish an exhibit public without displaying it in the collections list

### Use case 1
As a curator, I would like a to 'pre-publish' my site so that it does not display on the CURIOSity homepage, but I can share the link with colleagues for review before publishing.

Will be resolved by the new Viewer role in 3.0 once a view mask is created for it to turn this role back on.

### Use case 2
As a CURIOSity admin, I would like to hide the Terms of Use exhibit from the collections page, but still make them accessible via URL without logging in.

Note: This should be something only a CURIOSity admin can enable/disable for tracking purposes. 

This is not resolved by the new Viewer role. Is there a better solution for the Terms of Use? Revisit moving it to Lib.H?

- [x] Temporarily solved by https://github.com/scientist-softserv/harvard-curiosity/pull/15
- [x] Revert these changes once a permanent solution is enabled

### Related issue
https://github.com/harvard-lts/CURIOSity/issues/100

**Comment by dl-maura** [comment]
It sounds like this is still pending? At least case 2

**Comment by VanessaVenti** [comment]
Yes, case 2 is still pending and we also have work to do to make the Viewer role work for case 1 as well as that functionality got hidden with the role masking work.

**Comment by VanessaVenti** [comment]
Will assess now, if we have time. The work will likely be done in a maintenance sprint. @phil-plencner-hl can you take a look at this one?

**Comment by mferrarini** [comment]
Card idea to hide the terms of use:

```
a[href="/terms-of-use"] {
   display: none;
}
```

**Comment by VanessaVenti** [comment]
@mferrarini and @phil-plencner-hl - I was thinking about what this might look like in the admin UI and was thinking a dropdown might make the most sense. The options could be:

- Published (Everyone can view without logging in AND card displays on the CURIOSity landing page.)
- Under Review (Everyone can view without logging in but card does NOT display on the CURIOSity landing page. Users must know the URL for access.)
- Unpublished (Only logged-in users with access can view and card does NOT display on the CURIOSity landing page)

Not sure if 'Under Review' is the best term, let me know if you have other ideas! Suggestions on the helper text are welcome as well.

**Comment by mferrarini** [comment]
Have implemented a short-term solution to hide the "Terms of Use" exhibit card from the homepage while still being accessible via a link. https://github.com/scientist-softserv/harvard-curiosity/pull/15

Once pre-published exhibits are working, this change will need to be reverted.

**Comment by VanessaVenti** [comment]
Looks good on QA!
