### ISSUE TITLE
Implement end user account features: Bookmarks, Saved Searches, and History

### ISSUE THREAD

**Issue by VanessaVenti** [harvard-lts/CURIOSity#56]
Currently the Bookmarks, Saved Searches, and History links are hidden. If/when they are turned back on, they should behave the same way as HDC. Ideally both HarvardKey and non-HarvardKey users should be able to use this feature, therefore https://github.com/harvard-lts/CURIOSity/issues/57 should be implemented simultaneously. 

This feature was requested for the BTA.

Outstanding questions/considerations:
- Does the research support users want this feature or do they save their items/searches elsewhere?
- Is this still an out-of-the box feature? Not seeing this capability. If so, is it session or based? Is it exhibit specific?
- When we first investigated this feature in 2018/19, most places had this feature turned off

**Comment by dl-maura** [comment]
This might be involved -- would also require logins for non-staff

**Comment by VanessaVenti** [comment]
User research shows that users want to manage their bookmarks in their own systems/tools rather than creating site specific accounts.
