### ISSUE TITLE
Add curiosity.library.harvard.edu

### ISSUE THREAD

**Issue by VanessaVenti** [harvard-lts/CURIOSity#59]
Add curiosity.library.harvard.edu as a URL in addition to curiosity.lib.harvard.edu

**Comment by dl-maura** [comment]
Ask comms if we can do this? How would this work? Redirect to lib.harvard?

**Comment by VanessaVenti** [comment]
@dl-maura ask Kerry Conley in HL Comms about this.

**Comment by dl-maura** [comment]
We've emailed Kerry and she responded, discuss today

**Comment by phil-plencner-hl** [comment]
We worked with HUIT () and Paul Johnston to resolve this. I will put Paul's note here for prosperity.

> Hope you don't mind a verbose explanation, to avoid misunderstandings in the future:
>  
> Ben is correct, he can't do a redirect from  [anything].library.harvard.edu  to  [anything].lib.harvard.edu  just with a static DNS record.  A redirect is an active process, done by a Web server or by a Web app, or by a router, or several other ways;  but not via DNS.
>  
> Here's an example:  The DNS name "hgl.harvard.edu" is an alias -- a.k.a. a CNAME record, as mentioned in Ben's response -- for the DNS name "hgl.lib.harvard.edu".  And you can access the HGL Web site using either name:
>  
> https://hgl.harvard.edu/
> https://hgl.lib.harvard.edu/
>  
> If you start off at the hgl.harvard.edu address, all the subsequent pages served from the Web site will have that root address.  And conversely if you start off at hgl.lib.harvard.edu, your entire session will have that root URL.  No redirect between sites, one is just an alias for the other.
>  
> Back to the main point:  the DNS name "curiosity.library.harvard.edu" is an alias for the DNS name "curiosity.lib.harvard.edu", which is how Ben interpreted Phil's request in [INC04693230](https://harvard.service-now.com/nav_to.do?uri=%2Fincident.do%3Fsys_id%3D0b2bacaa97ee151470b03d700153afd1%26sysparm_stack%3D%26sysparm_view%3D).  And just like with HGL, you can start off at either of these URLs and keep the same root address all the way through your session:
>  
> https://curiosity.library.harvard.edu/
> https://curiosity.lib.harvard.edu/
>  
> You'd get an SSL certificate warning for curiosity.library and you'd have to tell your browser to go ahead anyway;  but the basic pattern is the same as for HGL.
>  
> So why does  http://curiosity.library.harvard.edu/  appear to work the way you want?  Because there must be a redirect built into the Curiosity app, which actively redirects any plain HTTP requests to  https://curiosity.lib.harvard.edu/.  That isn't done by the DNS record, and it isn't done by anything in the AWS configuration  -- I checked  --  so it must be coming from the app itself.
>  
> Since https://curiosity.library  is already an HTTPS request, it doesn't fit that redirect rule and doesn't get redirected.

and

> Okay, that was pretty simple, the redirect is set up on the load balancer and seems to work as desired.
>  
> The only problem is that the browser checks the SSL certificate before the redirect happens, and the SSL certificate doesn't cover curiosity.library;  so you still get a certificate warning.
>  
> I'll request a new cert....
