### ISSUE TITLE
Recreate no thumbnail/viewer theme

### ISSUE THREAD

**Issue by VanessaVenti** [harvard-lts/CURIOSity#62]
This theme is used on collections where the record itself is the data (there is no digital object attached to the record). Collections currently using this theme are:
- [A-Cats courses](https://curiosity.lib.harvard.edu/archived-harvard-university-online-course-catalogs-courses)
- [A-Cats calendars](https://curiosity.lib.harvard.edu/archived-harvard-university-online-course-catalogs-calendars)
- [A-Cats faculty](https://curiosity.lib.harvard.edu/archived-harvard-university-online-course-catalogs-faculty)
- [Ming Dynasty Paintings](https://curiosity.lib.harvard.edu/index-ming-dynasty-chinese-paintings)
- [Iranian Oral History Project](https://curiosity.lib.harvard.edu/iranian-oral-history-project)

**Comment by summer-cook** [comment]
### QA: Passed

This work is on staging

Configuration allowing theme changes:
<img width="500" alt="Screen Shot 2022-05-18 at 3 27 56 PM" src="https://user-images.githubusercontent.com/73361970/169150027-9bec1184-c263-4d9d-a374-faba8e729e74.png">


No thumbnail on search results:

<img src='https://user-images.githubusercontent.com/73361970/169150088-04348b48-41ec-41d4-b562-58ce3f403a99.png' width=500 />


No viewer on item-show page:

<img src='https://user-images.githubusercontent.com/73361970/169150197-cd857934-713e-4097-9071-a821b8d22557.png' width=500 />
