### ISSUE TITLE
Investigate changing an exhibit's URL

### ISSUE THREAD

**Issue by VanessaVenti** [harvard-lts/CURIOSity#69]
As a curator, I may want to change an exhibit's URL after the initial exhibit has been set up for a couple of reasons, 1) the collection title has changed, 2) when creating an exhibit initially, I had one scope in mind and then decided later to expand or narrow the scope. 

Can this be easily changed on the back end? If so, how will it effect item URLs and permalinks?

**Comment by dl-maura** [comment]
It is probably better to just make a new exhibit and import into that

**Comment by VanessaVenti** [comment]
Since we were able to successfully export/import most exhibits from 2.0 to 3.0, hopefully the same is true from 3.0 to 3.0 or whatever version we are on going forward. As @dl-maura notes, this is likely the best solution rather than trying to change the URL of an existing exhibit.
