### ISSUE TITLE
Harvard -- Get Test Suite Up and Running -- Ensure Tests are Passing

### ISSUE THREAD

**Issue by crisr15** [harvard-lts/CURIOSity#7]

**Comment by VanessaVenti** [comment]
We have a working Harvard QA - @dl-maura and @phil-plencner-hl are the tests passing? If so, I think we can close this ticket.

**Comment by dl-maura** [comment]
This is actually a different thing @VanessaVenti having to do with outrunning tests -- we haven't tried to get the test suite out of gitlab and into GitHub yet

**Comment by VanessaVenti** [comment]
Ah, thanks for the info @dl-maura - I'll leave this one open for you and Phil then!

**Comment by dl-maura** [comment]
@enriquediaz @phil-plencner-hl do we want to talk about bringing over the tests softest wrote and putting them into our pipeline?

**Comment by VanessaVenti** [comment]
Maura C. and Phil will pair on this.

**Comment by phil-plencner-hl** [comment]
Softserve's Test actions are here:
https://github.com/scientist-softserv/actions/blob/main/.github/workflows/test.yaml

This needs to be moved into our own repository.

Tests in the `spec` directory can be run inside the container this way:

```
bundle exec bin/rails db:test:prepare # only needs to be run once
bundle exec bin/rspec
```

Probably need to update this portion of the Github Action to run our local test workflow if it is our environment:

https://github.com/scientist-softserv/harvard-curiosity/blob/main/.github/workflows/build-test-lint.yaml#L24-L29

**Comment by phil-plencner-hl** [comment]
The scientist tests were way more complex than what we need for our circumstances. I ended up basing a new GitHub action off of the action we are using in HGL with some minor updates (changing db to postgres, updating rails version and bundle version used etc).

Action runs and the tests pass. 

PR is here: https://github.com/scientist-softserv/harvard-curiosity/pull/8

Successful Action/Test here: 
https://github.com/scientist-softserv/harvard-curiosity/actions/runs/3525513879

cc: @VanessaVenti  @dl-maura
