### ISSUE TITLE
Constraints not appearing in search results

### ISSUE THREAD

**Issue by summer-cook** [harvard-lts/CURIOSity#73]
# Summary

- the Constraints are not appearing- most likely need to be configured. this would likely be done in the catalog controller (similar to what needed to be done for the [view types](https://github.com/harvard-lts/CURIOSity/issues/70)  in this ticket.

# Notes

- it looks like constraints are rendered by the BlacklightAdvancedSearch gem
- Stanford has their constraints working: they include `BlacklightAdvancedSearch:Controller` in their catalog controller

**Comment by enriquediaz** [comment]
They appear now!
