### ISSUE TITLE
Header refinement

### ISSUE THREAD

**Issue by VanessaVenti** [harvard-lts/CURIOSity#81]
### Aspect ratio of masthead image
For the masthead image, the crop tool indicator does not reflect the actual cropping displayed in the masthead. It appears to be displaying just the left half of the image and also changes depending on the length of the title/presence of subtitle (see screenshots below). I remember this happening when we first investigated changing the aspect ratio of the masthead image and I'm hoping @phil-plencner-hl can remember what he did to get it to work. What if we kept it the same size/aspect ratio for all title lengths and the font size of the title decreased for longer titles? The short title with a subtitle (the middle option) seems like a good target/aspect ratio to aim for. 

**Crop tool indicator**
![Image](https://user-images.githubusercontent.com/60190174/169531553-bff0e0c2-0bff-4d7a-b027-18a31b2c1104.png)

 **Short title - no subtitle**
![Image](https://user-images.githubusercontent.com/60190174/169531633-a386060d-8ab1-43e5-b1d6-76cc294c868a.png)

**Short title - with subtitle**
![Image](https://user-images.githubusercontent.com/60190174/169531725-6f8ec66a-6701-4103-95ac-611fd47aea66.png)

**Long title - with subtitle**
![Image](https://user-images.githubusercontent.com/60190174/169531790-74deb3d8-67fe-4c6f-be71-2bbe7ee9998f.png)

### Subtitle
- Unbold the subtitle

### Main nav
- Increase right/left margins to reduce the overall width of the teal
- Increase spacing between nav items
- Reduce height of teal nav - looks like we have it at about 60px now
The live site is a good guide https://curiosity.lib.harvard.edu/demo (with the exception of the search box, you can leave that how you have it now)

**Live site screenshot**
![Image](https://user-images.githubusercontent.com/60190174/169533006-7e6602b1-6fa1-48a0-b48f-d61dc82a2109.png)

**Comment by summer-cook** [comment]
Hi @VanessaVenti !

Just taking a look at this ticket and wanted to make a note about:

What if we kept it the same size/aspect ratio for all title lengths and the font size of the title decreased for longer titles?

^ this can be done, but would require adding some custom javascript to make the font sizes dynamic based on text-length, since the number of letters is inputted by the user.

Everything else on this ticket is quick though, so i may split off that top part into a separate ticket to get the other parts across the line. Does that work?

**Comment by VanessaVenti** [comment]
@summer-cook - that works, thanks! It's possible we could find a single font size that works for both long and short titles with that middle size option. I think we'll just have to see what it looks like.

**Comment by summer-cook** [comment]
@VanessaVenti when it comes to finding a single font size that works for both long and short titles: i can build it with your longest title & subtitle as an example-making sure they stay on a single line each, and and then just use regular CSS media queries from there to make the font smaller as the window width gets smaller. that may be a simpler option than adding JS, but i think it would make the title pretty small.
If you are okay with that, i can try it with the longest title: 'Archived Harvard University Online Course Catalogs (A-Cats) - Calendars' and i'm not sure what the longest subtitle is.

**Comment by VanessaVenti** [comment]
@summer-cook That sounds like a good plan. It looks like our longest subtitle is "Sponsored Exploration and Scientific Discovery in the Modern Age". And it looks like our longest title/subtitle combo is "Slavery, Abolition, Emancipation and Freedom / Primary Sources from Houghton Library"
