### ISSUE TITLE
Migrate 2.0 exhibits to 3.0

### ISSUE THREAD

**Issue by bkiahstroud** [harvard-lts/CURIOSity#88]
# Summary
Transfer of exhibits from old site to new prod (beta).

# Before Beta move
- [x] https://github.com/harvard-lts/CURIOSity/issues/195 (VV and AVS)
- [x] [Notify curators of exhibit editing freeze](https://docs.google.com/document/d/1blcLYbsTpPbS7fiJmu9JfNx21HlDHHgXFqJrPCtF3MI/edit#heading=h.6316h0sghg40) (VV notified curators on 12/6)
- [x] https://github.com/harvard-lts/CURIOSity/issues/231 (MC)
- [x] Merge curiosity-bta.yml with curiosity.yml (VV has merged file, but it needs to be uploaded to Github and cleaned up in Spotlight)
- [x] Mint new prod image (code freeze) (MC + PP)
- [x] IF project updates
- [x] Redeploy beta (MC + Ops)

# Move to beta
See [Collection Migration Checklist](https://docs.google.com/spreadsheets/d/1umOrtOraA_cBrhzzwgXD_hAD4xE14v0HYGl0LENK4tQ/edit?usp=sharing) for status of each collection
- [x] Remove curators as admins from 2.0 sites (VV)
- [x] Export exhibit jsons from 2.0 prod (VV)
- [x] Add exhibit ID to json (VV)
- [x] Upload 2.0 jsons to [Google drive folder](https://drive.google.com/drive/folders/1bxlPxQanRL2botAHeACIuxuDV-WXfsTc?usp=share_link) (VV)
- [x] Copy image and database tables from 2.0 to 3.0 (MC and PP)
- [x] Create new exhibits in 3.0 (MC and PP) 
- [x] Upload 2.0 jsons to 3.0 (MC and PP)
- [x] [Harvest items](https://github.com/harvard-lts/CURIOSity/issues/38) (VV) 
- [x] Verify metadata (VV)
  - [x] Delete 'Creation Date' and 'Harvard Digital Collections' (if it appears) exhibit specific fields
  - [x] Fix order of metadata fields and make sure the check boxes match prod
  - [x] botanicals - make sure Collection appears and that Rights is renamed to Access
  - [x] epj - has exhibit specific Shelf location field
  - [x] hedda - has exhibit specific Shelf location field
  - [x] horblit - Genre facet is renamed to Format
- [x] Verify exhibit content (pages and illustrative images) transferred successfully (VV and AVS)
  - [x] Recrop masthead, thumbnail, and browse category images to use new aspect ratio
  - [x] Recreate items in widgets so new image sizes are applied (json appears to save old image sizes, deleting the item in the widget and adding it back in fixes the issue)
  - [x] Replace all occurrences with iFrame widget or Item Row widget, see [Item embed widget occurrences spreadsheet](https://docs.google.com/spreadsheets/d/1OhmbNoP8vGCE3cBsp-CEAIt58-muXvNq9_rG2hrxbbc/edit?usp=sharing) for details (VV and AVS)

# Starting December 19th, 2022
- [x] Curator review

# January 17th, 2023
- [x] Cutover to 3.0 (Dev ops)
- [x] Notify curators of cutover and ongoing edit freeze until db fix on 1/19 (VV)

# January 19th, 2023
- [x] Deploy DB fix so image links don't resolve to beta
- [x] Notify curators of cutover and need to set up their account so they can edit the new sites (VV)

# Notes
- We considered adding "is_multiple": true to the custom fields (after "readonly_field") in the jsons before importing to 3.0. We decided it was not necessary because they appear to be working in 3.0 when harvesting Q.A (see Annotator in JSBD) and we don't have a current use case for editing metadata manually which is what this option is needed for. If we do end up editing metadata manually, this will need to be fixed in both our custom and default fields (adding "is_multiple to the 2.0 jsons for the 3.0 defaults before importing did NOT enable this button). Kiah noted custom fields do behave a little differently than the default fields. Collections with the most custom fields are: BTA, JBSD, MPCOL, IOHP, Ming Paintings, and A-CATS. Botanicals, epj, and hedda each have one. The rest of the sites should only have a permalink as a custom field.

**Comment by dl-maura** [comment]
We are actively working on this (iteration), this can only be done on Harvard so moving to Harvard QA

**Comment by VanessaVenti** [comment]
@dl-maura I don't think we're quite ready for this yet. I still need to test all the metadata stuff is working as expected and notify the curators about the freeze. Probably some other things need to be checked too.

**Comment by VanessaVenti** [comment]
Successfully cut over on 1/17/2023 and put in db fix on 1/19/2023 to put beta fully into production!
