### ISSUE TITLE
Review of Overrides and Features on Vanilla Spotlight

### ISSUE THREAD

**Issue by crisr15** [harvard-lts/CURIOSity#9]
# Summary

In order to determine what work should be done, and to make sure to take full advantage of the features from the newest spotlight version we need to analyze what overrides should be moved over, what needs to be changed, and what new features of spotlight should be used.  

# Acceptance Criteria
- [x] Explore the Vanilla instance of spotlight to play with new features
- [x] Determine list of features that need to be transfered to the new app and update/make issues for them. 
- [x] Determine what features will need to change how they work and update/make issues for them.  
- [x] Determine what previous features should be ignored or removed in favor of spotlight features.  Close any open issues and document this list for future understanding
- [x] Order issues by order of importance on the board.

**Comment by VanessaVenti** [comment]
@crisr15 For the admin dashboard below are screenshots showing what we've moved or added in 2.0. https://github.com/harvard-lts/CURIOSity/issues/51 lists additional enhancement requests.

### General
Added an Exhibit ID field
Also note in the left nav we moved Items and Tags under Configuration. In 3.0 we would like to move Bulk updates here as well.
![Admin - General](https://user-images.githubusercontent.com/60190174/164069267-6fd36063-d43f-4ffc-8be7-7d86a7b18b18.png)

### Appearance
Added a Visual Theme tab
![Admin - Appearance](https://user-images.githubusercontent.com/60190174/164069539-3be866d4-d393-4f68-a131-e3a0bc1d98cf.png)

### Add items
Here's what our From External Resource tab looks like for harvesting via OAI-PMH:
![Admin - Add items](https://user-images.githubusercontent.com/60190174/164069907-2d421744-75aa-4cb0-909a-62943fbff398.png)
