### ISSUE TITLE
[1] Increase Requested Thumbnail size

### ISSUE THREAD

**Issue by crisr15** [harvard-lts/CURIOSity#92]
Some of the exhibit item widgets appear to be stretching/enlarging the thumbnail image and therefore display a poor quality/pixelated images. The Item Carousel Widget and the Item Grid Widget look particularly bad because of this. Other widgets such as the Item Row and Item Slideshow display rather small images. Examples of all widgets in use on this page: https://curiosity.lib.harvard.edu/demo/feature/exhibit-item-widgets. Anthony recommends requesting an image larger than 180px (perhaps 300px?). This will require all collections to be reharvested.

**Comment by crisr15** [comment]
app/uploaders

**Comment by summer-cook** [comment]
this is actually not happening in spotlight itself: it is happening in this line in the spotlight_oaipmh_resources gem: https://github.com/harvard-lts/spotlight-oaipmh-resources/blob/b8985388d1e54c8d5c5d25c249cf056679469fb3/app/services/spotlight/resources/oaipmh_builder.rb#L165

**Comment by VanessaVenti** [comment]
I'm seeing them come through as 300px on QA now, but we #148 to increase it to 600px to improve the quality further. I'll close this one.
