### ISSUE TITLE
Full Text Search - Front End Changes

### ISSUE THREAD

**Issue by crisr15** [harvard-lts/CURIOSity#96]
- Add box for searching full text instead of solr query.
- view changes and results for full text search

**Comment by dl-maura** [comment]
Adding some details here:

- we will need to add a new field to the exhibit metadata for FTS Set Name, this will be manually entered (as Library Cloud has no knowledge of FTS sets). That will provide the info for the api call
- we do have sets ready to go, I've posted in slack an example of the UI search, but let me know if you need other things as well

**Comment by dl-maura** [comment]
This ticket is for:
FTS Serach Checkbox
Message letting you know you're doing FTS Search
FTS Match highlighting
FTS 1 of x pages results per item
