### ISSUE TITLE
Full Text Search - Logic and Call Related

### ISSUE THREAD

**Issue by crisr15** [harvard-lts/CURIOSity#97]
- API call for full text search (probably pulling context and result text size)
- Query solr for IDs passed back from the API.
- How do the sets work from spotlight to pull only the FTS results from the individual exhibit - a new field will need to be added to spotlight that allows the admin to add the FTS set for searching.

**Comment by summer-cook** [comment]
- the user will either search regular Spotlight Solr Search (only looks at metadata) or they will search the API
- when you check the button that selects full text search under the search bar, it switches to searching the API

**Comment by summer-cook** [comment]
- we will need to add setName at the exhibit level so it will match up with the setName and we can make the API call successfully
-

**Comment by bkiahstroud** [comment]
### Investigation on GitLab `main@f532f352`

#### 1) Hidden pagination 

<details><summary>Screenshots</summary>

![Image](https://user-images.githubusercontent.com/32469930/187554207-4c0371c1-7a8e-49fa-a7f8-d1d0f95e237e.jpg)
![Image](https://user-images.githubusercontent.com/32469930/187554206-f1169abf-6a95-4235-918a-6b1841cc2227.jpg)


</details>

---

**Comment by bkiahstroud** [comment]
Related: https://gitlab.com/notch8/harvard-curiosity/-/merge_requests/146/diffs

**Comment by dl-maura** [comment]
We have split this into its own ticket:
[#178](https://github.com/harvard-lts/CURIOSity/issues/178)

as we are now seeing results (which need fixing) but this ticket was really about the blank display. Closing and will use the new ticket
