### ISSUE TITLE
Full Text Search - After Mirador

### ISSUE THREAD

**Issue by crisr15** [harvard-lts/CURIOSity#98]
# Summary 

When doing a search including full text search and clicking on the results link you should go to the item page in the exhibit.  If full text is available with a page in the full text search data the mirador viewer will open to the first page with a result.  

# Acceptance Criteria
- [x] When searching a work with full text search, if the results were found and a pageOrder attribute is available, the item will open in the viewer to the first page the results show.

**Comment by crisr15** [comment]
The mirador viewer now opens to the correct page if the query was found in FTS. This is based on the pageOrder attribute described above. Their Mirador viewer does not highlight text when searching.

**Comment by dl-maura** [comment]
Tested in QA, we did open to the first page of results on an item (opened to page 349 which had the hit for the word)
